### ISSUE TITLE
Error: Unexpected DefinitionNode sub-type: [object Object]

### ISSUE THREAD

**Issue by dcolthorp** [dotansimha/graphql-code-generator#141]
Hello!

I just tried updating `graphql-code-generator` from 0.5.5 and my schema no longer works. It appears this changed with 0.8.0 and is still broken in 0.8.10.

Let me know if I'm just doing something wrong – but this schema used  to work.

The error is:

```
>  yarn run  gql-gen -- --file schema.json  --template typescript --out schema-types.ts schema.graphql
yarn run v0.24.6
$ "/Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/.bin/gql-gen" --file schema.json --template typescript --out schema-types.ts schema.graphql
Loading GraphQL Introspection from file: schema.json...
Error: Unexpected DefinitionNode sub-type: [object Object]
    at /Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/graphql-codegen-core/dist/operations/transform-document.js:24:19
    at Array.forEach (native)
    at transformDocument (/Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/graphql-codegen-core/dist/operations/transform-document.js:16:17)
    at Object.<anonymous> (/Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/graphql-code-generator/dist/cli.js:138:43)
    at step (/Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/graphql-code-generator/dist/cli.js:32:23)
    at Object.next (/Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/graphql-code-generator/dist/cli.js:13:53)
    at fulfilled (/Users/colthorp/Repositories/ts-react-graphql-starter-kit/node_modules/graphql-code-generator/dist/cli.js:4:58)
    at <anonymous>
Error: Error: Unexpected DefinitionNode sub-type: [object Object]
error Command failed with exit code 1.
```

Here are the `schema.graphql` and `schema.json` I was using.

[bad-schema.zip](https://github.com/dotansimha/graphql-code-generator/files/1198484/bad-schema.zip)

**Comment by mellocello2003** [comment]
I ran into this as well.

**Comment by dotansimha** [comment]
Working on it. Thank you for the attachment, it's really helpful!

**Comment by dotansimha** [comment]
Ohh I see why it happens.
Your `schema.graphql` is not a valid GraphQL file, because it contains the schema it self.

You provided the schema using `--file`, so either don't provide your schema again as the last parameter for the CLI, or provide client-side documents (query, fragment, mutation ... ) in the last param.

So it should be:
```
yarn run  gql-gen -- --file schema.json  --template typescript --out schema-types.ts
```

Or, if you have queries and you want to generate typings for the queries:
```
yarn run  gql-gen -- --file schema.json  --template typescript --out schema-types.ts ./queries/*.query.graphql`
````
