### ISSUE TITLE
Cannot find module 'graphql/language/parser'

### ISSUE THREAD

**Issue by hkjeffchan** [dotansimha/graphql-code-generator#191]
npm -g ls graphql-code-generator
/usr/local/lib
└── graphql-code-generator@0.8.18

gql-gen --file schema.json --template typescript --out ./typings/

module.js:540
    throw err;
    ^

Error: Cannot find module 'graphql/language/parser'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/graphql-code-generator/node_modules/graphql-tag/lib/graphql-tag.umd.js:7:14
    at /usr/local/lib/node_modules/graphql-code-generator/node_modules/graphql-tag/lib/graphql-tag.umd.js:2:65
    at Object.<anonymous> (/usr/local/lib/node_modules/graphql-code-generator/node_modules/graphql-tag/lib/graphql-tag.umd.js:5:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

**Comment by hkjeffchan** [comment]
npm -g install graphql

**Comment by dotansimha** [comment]
@hkjeffchan I added it to the README. Thanks!
