### ISSUE TITLE
Homepage 'try it out' section is broken

### ISSUE THREAD

**Issue by moodysalem** [dotansimha/graphql-code-generator#1959]
**Describe the bug**
The home page try it out section is broken for me

**To Reproduce**

1. Visit https://graphql-code-generator.com/
2. Click try it out, which navigates to the next section
3. Nothing there to try out
4. Errors in the console

```
11.a655f578.chunk.js:1 Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:397878
    at g (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:397981)
    at U (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:401138)
    at Object.useContext (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:402064)
    at a (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:579192)
    at https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:15432
    at https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:18267
    at qi (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:137334)
    at ko (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:143321)
    at Io (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:151904)
pa @ 11.a655f578.chunk.js:1
11.a655f578.chunk.js:1 Uncaught Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:397878
    at g (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:397981)
    at U (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:401138)
    at Object.useContext (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:402064)
    at a (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:579192)
    at https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:15432
    at https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:18267
    at qi (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:137334)
    at ko (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:143321)
    at Io (https://graphql-code-generator.com/live-demo/static/js/11.a655f578.chunk.js:1:151904)
```

**Expected behavior**
I used to see the section with 3 inputs that let me put in schema, queries, and select a language plugin, but now I see this error about hooks. It's been broken for me at least a few days now. I tried clearing the cache and app settings and disabling cache and nothing seems to fix it, so it seems like an actual code bug

**Environment:**

Google Chrome | 74.0.3729.169 (Official Build) (64-bit)
OS | Linux
JavaScript | V8 7.4.288.28
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by dotansimha** [comment]
Fixed now, thanks @moodysalem !
