### ISSUE TITLE
'Error: Must provide valid Document AST' when trying to use programmatic API

### ISSUE THREAD

**Issue by mhank** [dotansimha/graphql-code-generator#2061]
**Describe the bug**
I've written a script that's supposed to feed a schema from a remote URL to the `codegen` function exported by `@graphql-codegen/core`. When the script is run, the following error is unexpectedly output:

```
Error: Must provide valid Document AST
    at invariant (/Users/mhankin/Code/sched/scheduling-framework/node_modules/graphql/jsutils/invariant.js:19:11)
    at Object.buildASTSchema (/Users/mhankin/Code/sched/scheduling-framework/node_modules/graphql/utilities/buildASTSchema.js:73:88)
    at Object.executePlugin (/Users/mhankin/Code/sched/scheduling-framework/node_modules/@graphql-codegen/core/dist/commonjs/execute-plugin.js:20:36)
    at codegen (/Users/mhankin/Code/sched/scheduling-framework/node_modules/@graphql-codegen/core/dist/commonjs/codegen.js:25:47)
    at /Users/mhankin/Code/sched/scheduling-framework/scripts/generate-backend-types.js:37:24
    at Object.<anonymous> (/Users/mhankin/Code/sched/scheduling-framework/scripts/generate-backend-types.js:43:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

**To Reproduce**
Here's the full script being run:

```js
const fs = require('fs');
const path = require('path');
const codegen = require('@graphql-codegen/core').codegen;
const typescriptPlugin = require('@graphql-codegen/typescript').plugin;
const typescriptOperationsPlugin = require('@graphql-codegen/typescript-operations')
	.plugin;
const typescriptReactApolloPlugin = require('@graphql-codegen/typescript-react-apollo')
	.plugin;

const schemaUrl = 'http://localhost:10033/v1/graphql';
const outputFile = '../src/generated/scheduling-framework-backend.tsx';

const config = {
	filename: outputFile,
	schema: schemaUrl,
	plugins: [
		{ typescript: {} },
		{ typescriptOperations: {} },
		{ typescriptReactApollo: {} },
	],
	pluginMap: {
		typescript: {
			plugin: typescriptPlugin,
		},
		typescriptOperations: {
			plugin: typescriptOperationsPlugin,
		},
		typescriptReactApollo: {
			plugin: typescriptReactApolloPlugin,
		},
	},
};

(async () => {
	try {
		const output = await codegen(config);
		await fs.writeFile(path.join(__dirname, outputFile), output);
		console.log('Types generated!');
	} catch (error) {
		console.error('Error generating types:', error);
	}
})();
```

**Expected behavior**
The `codegen` function is invoked without error and returns types corresponding to the given schema.

**Environment:**

- OS: MacOS Mojave
- `@graphql-codegen/core`: 1.3.1
- `@graphql-codegen/typescript`: 1.3.1
- `@graphql-codegen/typescript-operations`: 1.3.1
- `@graphql-codegen/typescript-react-apollo`: 1.3.1 
- NodeJS: 12.4.0

**Additional context**
This issue arose while troubleshooting #1987.

**Comment by dotansimha** [comment]
Hi @mhank ,
I think it caused because you are passing `schemaUrl` as schema, and with the programattic API you must provide the `GraphQLSchema` object and not url.
You can use `loadSchema` from `graphql-toolkit` to do load `GraphQLSchema` from a url string.

Also, I noticed that you are doing this in your code:

```
const typescriptPlugin = require('@graphql-codegen/typescript').plugin;

// ...

	pluginMap: {
		typescript: {
			plugin: typescriptPlugin,
		},
```

But not that this way you ignore other functionality of the plugin (such as `validate`). 

It should be:

```
const typescriptPlugin = require('@graphql-codegen/typescript');

// ...

	pluginMap: {
		typescript: typescriptPlugin,
```
```

**Comment by mhank** [comment]
@dotansimha unfortunately, making all of the changes you suggested did not resolve the error.

Updated script:
```js
const fs = require('fs');
const path = require('path');
const loadSchema = require('graphql-toolkit').loadSchema;
const codegen = require('@graphql-codegen/core').codegen;
const typescriptPlugin = require('@graphql-codegen/typescript');
const typescriptOperationsPlugin = require('@graphql-codegen/typescript-operations');
const typescriptReactApolloPlugin = require('@graphql-codegen/typescript-react-apollo');

const schemaUrl =
	'https://scheduling.nonprod.athena.io/scheduling-framework-backend/v1/graphql';
const schema = loadSchema(schemaUrl);
const filename = '../src/generated/scheduling-framework-backend.tsx';

const config = {
	filename,
	schema,
	plugins: [
		{ typescript: {} },
		{ typescriptOperations: {} },
		{ typescriptReactApollo: {} },
	],
	pluginMap: {
		typescript: typescriptPlugin,
		typescriptOperations: typescriptOperationsPlugin,
		typescriptReactApollo: typescriptReactApolloPlugin,
	},
};

codegen(config)
	.then((output) => {
		fs.writeFile(path.join(__dirname, filename), output, () =>
			console.log('Types generated!')
		);
	})
	.catch((error) => console.error('Error generating types:', error));
```

Still outputs the same error:
```
Error: Must provide valid Document AST
    at invariant (/Users/mhankin/Code/sched/scheduling-framework/node_modules/graphql/jsutils/invariant.js:19:11)
    at Object.buildASTSchema (/Users/mhankin/Code/sched/scheduling-framework/node_modules/graphql/utilities/buildASTSchema.js:73:88)
    at Object.executePlugin (/Users/mhankin/Code/sched/scheduling-framework/node_modules/@graphql-codegen/core/dist/commonjs/execute-plugin.js:20:36)
    at codegen (/Users/mhankin/Code/sched/scheduling-framework/node_modules/@graphql-codegen/core/dist/commonjs/codegen.js:25:47)
    at Object.<anonymous> (/Users/mhankin/Code/sched/scheduling-framework/scripts/generate-backend-types.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
```

**Comment by dotansimha** [comment]
Hi @mhank, `loadSchema` is `async`. You should wrap it with `await`.
