### ISSUE TITLE
should I be able to run tests?

### ISSUE THREAD

**Issue by petecarapetyan** [dotansimha/graphql-code-generator#2651]
When I git clone this repo, should I be able to run the tests successfully? Or are there other dependencies than those that `npm install` would take care of?

I ran `npm run test` and it launched the appropriate command, but it came back almost immediately as an error without much, if any, description

**Comment by n1ru4l** [comment]
I have no problems running the test after doing a yarn install.

**Comment by petecarapetyan** [comment]
For these versions:
yarn: 1.19.0
npm: 6.4.1
node: 10.13.0

History:
  ```
git clone git@github.com:dotansimha/graphql-code-generator.git
  cd graphql-code-generator/
  yarn install
  npm run test
```

Result:
```
lerna ERR! yarn run test exited 1 in '@graphql-codegen/fragment-matcher'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
npm info lifecycle @~test: Failed to exec test script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `lerna run test --ignore @graphql-codegen/{live-demo,website} `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
```
providing, just in case this helps.

**Comment by ardatan** [comment]
@petecarapetyan Could you share the full log?

**Comment by dotansimha** [comment]
@petecarapetyan Our repo is structured as mono-repo, using Yarn.
Please install latest Yarn and then run: `yarn` in the run directory to install dependencies for all sub-packages. Then you should be able to run `yarn test` in the root.

**Comment by petecarapetyan** [comment]
Since this was closed, I assume that the team is not interested (runs on my box, so it's not an issue)
I will not concern myself further, until I need to actually run tests.

Here is my run, per @dotansimha above
```
$ yarn
yarn install v1.19.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.02s.
```
and
```
$ yarn test
yarn run v1.19.0
$ lerna run test --ignore @graphql-codegen/{live-demo,website} 
lerna notice cli v3.16.4
lerna info filter [ '!@graphql-codegen/live-demo' ]
lerna info Executing command in 26 packages: "yarn run test"
lerna info run Ran npm script 'test' in '@graphql-codegen/plugin-helpers' in 1.6s:
$ jest --config ../../../jest.config.js
lerna ERR! yarn run test exited 1 in '@graphql-codegen/fragment-matcher'
lerna ERR! yarn run test stdout:
$ jest --config ../../../../jest.config.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:
ts-jest[config] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
FAIL tests/plugin.spec.ts
  ● Test suite failed to run

    Cannot find module '@graphql-codegen/testing' from 'plugin.spec.ts'

    > 1 | import '@graphql-codegen/testing';
        | ^
      2 | import { buildASTSchema, parse } from 'graphql';
      3 | import { codegen } from '@graphql-codegen/core';
      4 | import gql from 'graphql-tag';

      at Resolver.resolveModule (../../../../node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (tests/plugin.spec.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.809s
Ran all test suites.
error Command failed with exit code 1.

lerna ERR! yarn run test exited 1 in '@graphql-codegen/fragment-matcher'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dotansimha** [comment]
@petecarapetyan You just need to run `yarn build` before, otherwise you don't have the artifact of each package :)
