### ISSUE TITLE
Scalar type some time causes a syntax error in complied files.

### ISSUE THREAD

**Issue by tajpouria** [dotansimha/graphql-code-generator#2740]
Scalar type **some times** causes a syntax error in complied files.

[schema.graphql](https://github.com/tajpouria/graphql-wikipedia/blob/master/packages/graphql-wikipedia/src/modules/wikipedia/opensearch/schema.graphql)

**To Reproduce**

1. My GraphQL schemas:
src/module/opensearch/schema.ts
```graphql
# HERE IS THE PROBLEM
scalar Any
type Actions {
    """
    Search the wiki using the OpenSearch protocol.
    """
    opensearch(
        "Search string. This parameter is required"
        searchString: String!
        "customize openSearch action."
        openSearchOptions: OpenSearchOptions
    ): [Any]!
}

"""
customize openSearch action
"""
input OpenSearchOptions {
    "Namespaces to search.Default:0.(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|100|101|108|109|118|119|446|447|...)"
    namespace: Int = 0

    "Maximum number of results to return.Default:10"
    limit: Int = 10

    "Search profile to use.Default:engineAutoselect(strict|normal|fuzzy|fastFuzzy|classic|engineAutoselect)"
    profile: Profile = engineAutoselect

    "Do nothing if $wgEnableOpenSearchSuggest is false.Default:true"
    suggest: Boolean = true

    "The format of the output.Default:json"
    format: ResponseDataFormat

    "If warnings are raised with format=json, return an API error instead of ignoring them.Default:false"
    warningaserror: Boolean
}

"""
Search profile to use
"""
enum Profile {
    strict
    normal
    fuzzy
    fastFuzzy
    classic
    engineAutoselect
}

```
2. My `codegen.yml` config file:
```yml
overwrite: true
schema: "http://localhost:4000/graphql"
documents: null
generates:
    src/generated/graphql.ts:
        config:
            contextType: ../types/modules/context#APIEmbeddedContext
        plugins:
            - "typescript"
            - "typescript-resolvers"
            - "flow-resolvers"
            - "typescript-document-nodes"

```

**Expected behavior**

Some times it generate graphql(generated file) file correctly and sometimes not.

**Environment:**

- OS: ubuntu 16.8
- NodeJS: 10.16.3

**Additional context**
./lib/genrated/graphql.js
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/** Search profile to use */
var Profile;
(function (Profile) {
    Profile["Strict"] = "strict";
    Profile["Normal"] = "normal";
    Profile["Fuzzy"] = "fuzzy";
    Profile["FastFuzzy"] = "fastFuzzy";
    Profile["Classic"] = "classic";
    Profile["EngineAutoselect"] = "engineAutoselect";
})(Profile = exports.Profile || (exports.Profile = {}));
/** Represent fetched data format */
var ResponseDataFormat;
(function (ResponseDataFormat) {
    ResponseDataFormat["Json"] = "json";
    ResponseDataFormat["Jsonfm"] = "jsonfm";
    ResponseDataFormat["Xml"] = "xml";
    ResponseDataFormat["Xmlfm"] = "xmlfm";
})(ResponseDataFormat = exports.ResponseDataFormat || (exports.ResponseDataFormat = {}));
/** Represent fetched data language */
var WikipediaApiLanguage;
(function (WikipediaApiLanguage) {
    WikipediaApiLanguage["En"] = "en";
    WikipediaApiLanguage["Nl"] = "nl";
})(WikipediaApiLanguage = exports.WikipediaApiLanguage || (exports.WikipediaApiLanguage = {}));
'Any' > , any > , // THIS PART CAUSE AN ERROR
    name;
'Any';
;
````
console
```shell
examples: /home/tajpouria/.pro/fun/graphql-wikipedia/packages/graphql-wikipedia/lib/generated/graphql.js:27
[0] examples: 'Any' > , any > ,
[0] examples:         ^
[0] examples: SyntaxError: Unexpected token ,
[0] examples:     at Module._compile (internal/modules/cjs/loader.js:723:23)
[0] examples:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0] examples:     at Module.load (internal/modules/cjs/loader.js:653:32)
[0] examples:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0] examples:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0] examples:     at Module.require (internal/modules/cjs/loader.js:692:17)
[0] examples:     at require (internal/modules/cjs/helpers.js:25:18)
[0] examples:     at Object.<anonymous> (/home/tajpouria/.pro/fun/graphql-wikipedia/packages/graphql-wikipedia/lib/datasources/wikipediaAPI/optionsDefaultValues.js:3:17)
[0] examples:     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0] examples:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0] examples: [nodemon] app crashed - waiting for file changes before starting...
```
[Repo](https://github.com/tajpouria/graphql-wikipedia/tree/master/packages/graphql-wikipedia)

**Comment by ardatan** [comment]
@tajpouria You're trying to use `flow-resolvers` to generate `ts` file. Could you remove it and try again?

**Comment by dotansimha** [comment]
@ardatan is right, you are mixing Flow and TypeScript plugins. Please review you config file and let us know if the issues persists.

**Comment by tajpouria** [comment]
@ardatan Removing `flow-resolvers` plugin fixed the problem. tank you
