### ISSUE TITLE
Error: Cannot find module 'listr-update-renderer' on  "version": "1.9.0"

### ISSUE THREAD

**Issue by muzakparov** [dotansimha/graphql-code-generator#3025]
I am getting the following error while just trying to run it:
```
 Error: Cannot find module 'listr-update-renderer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bakhtiiar/Desktop/work/backoffice_gql_notes/node_modules/@graphql-codegen/cli/index.cjs.js:89:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[nodemon] app crashed - waiting for file changes before starting...
```

I use `yarn` and tried a few times removing `node_modules` and `yarn.lock`. Reinstalling didn't help unfortunately.

**Comment by muzakparov** [comment]
duplicate: https://github.com/dotansimha/graphql-code-generator/issues/3023#issuecomment-558963814

closing issue
