### ISSUE TITLE
v1.9.0 fails to find 'listr-update-renderer' module

### ISSUE THREAD

**Issue by sergsalo** [dotansimha/graphql-code-generator#3041]
Error: Cannot find module 'listr-update-renderer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/@graphql-codegen/cli/bin.js:159:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by sergsalo** [comment]
close as duplicate of #3023
