### ISSUE TITLE
TypeError: func is not a function

### ISSUE THREAD

**Issue by dauledk** [dotansimha/graphql-code-generator#3256]
When running `graphql-codegen` to generate typings,  our team suddenly started to get this error today, after months of working without issues. I updated to latest version of all plugins, but the issue persists.

```
TypeError: func is not a function
    at <path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:19
    at Array.map (<anonymous>)
    at convertNameParts (<path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:10)
    at opts (<path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:425:24)
    at Object.convert (<path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:462:43)
    at TsVisitor.convertName (<path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:488:78)
    at TsVisitor._getTypeForNode (<path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:889:21)
    at TsVisitor.NamedType (<path-to-project-folder>/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:892:21)
    at TsVisitor.NamedType (<path-to-project-folder>/node_modules/@graphql-codegen/typescript/index.cjs.js:101:31)
    at Object.visit (<path-to-project-folder>/node_modules/graphql/language/visitor.js:242:26)
    at Object.plugin (<path-to-project-folder>/node_modules/@graphql-codegen/typescript/index.cjs.js:195:35)
    at executePlugin (<path-to-project-folder>/node_modules/@graphql-codegen/core/index.cjs.js:50:41)
    at <path-to-project-folder>/node_modules/@graphql-codegen/core/index.cjs.js:106:30
    at Array.map (<anonymous>)
    at Object.codegen (<path-to-project-folder>/node_modules/@graphql-codegen/core/index.cjs.js:96:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**
Generated types

**Environment:**

- OS: MacOS 10.14.6
- "@graphql-codegen/cli": "^1.11.2",
- "@graphql-codegen/typescript": "^1.11.2",
- "@graphql-codegen/typescript-apollo-angular": "^1.11.2",
- "@graphql-codegen/typescript-operations": "^1.11.2",
- "@graphql-codegen/typescript-resolvers": "^1.11.2",
- NodeJS: 12.11.1

**Comment by evark** [comment]
some here...
until 1.9.1 everything is OK.
from 1.10.0 I get this error.

**Comment by dauledk** [comment]
I can confirm that the problem also starts with `1.10.0` in our project

**Comment by ardatan** [comment]
@dauledk @evark Could you reproduce it using this codesandbox template?
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template

**Comment by dauledk** [comment]
Hi @ardatan, to be honest, I don't know where to start - I am not very familiar with codesandbox. Given the link you provided me, how do I create an Angular project 🤷🏾‍♂️?
We are using an apollo express node.js + Angular project. I will just update the issue with our `codegen.yml` file, if it can maybe help. I was really hoping that the stack trace would tell you something 😅

**Comment by dauledk** [comment]
@ardatan I tried reproducing this error, it's not easy but I finally found something! It seems like the error is not related to the setup (client or server) at all - but has something to do with versioning - maybe npm.

When I removed the `package-lock.json` (something I otherwise always try to avoid as a solution) and did a fresh install with `npm i @graphql-codegen/{cli,typescript,typescript-apollo-angular,typescript-operations,typescript-resolvers}@latest`, the error was gone 🤔

Only thing is that now, I can't reproduce 🤷🏾‍♂️

**Comment by evark** [comment]
OK! after deleting node_modules/package-lock.json and reinstall everything codegen work normally. It seems that some dependency is not updated with normal update of the package. Full reinstall is needed.

**Comment by desbrowne** [comment]
In our case, the `pascal-case` dependency (v2.0.0) didn't match the included type definition. The type def is `import { pascalCase } from 'pascal-case'` where as the js seems to be exporting the func as default, e.g. `import pascalCase from 'pascal-case'`.

I just tried installing the latest version of pascal-case (v3.1.1) explicitly and it fixed the issue.

**Comment by saostad** [comment]
it looks graphql-codegen has a dependency of "change-case": "^3.0.0", but change-case has dependency of "pascal-case": "^2.0.0",
so I think we need to update change-case to latest version. 
`npm i -D change-case`

or wait for maintainers to update the dependency to "change-case": "^4.1.1"

**Comment by dotansimha** [comment]
@ardatan is it fixed?

**Comment by bezreyhan** [comment]
I just installed @graphql-codegen/cli on an existing project and hit this error. I tried deleting package-lock but that did not fix the issue. Downgrading to `v1.9.1` resolved it.

**Comment by aya-eiya** [comment]
this cause again in case using
```
"@graphql-codegen/typescript-operations": "1.17.15",
```
not cause on `1.17.14`.

**Comment by aya-eiya** [comment]
my other plugins and changed dependencies.
``` package.json 
  "devDependencies": {
    "@graphql-codegen/cli": "^1.21.2",
    "@graphql-codegen/typescript-operations": "1.17.14",
    "@graphql-codegen/typescript-react-query": "^1.2.3",
}
```

```diff
diff --git a/frontend/package.json b/frontend/package.json
index 05e7fbb..ffe7946 100644
--- a/frontend/package.json
+++ b/frontend/package.json
@@ -30,7 +30,7 @@
   },
   "devDependencies": {
     "@graphql-codegen/cli": "^1.21.2",
-    "@graphql-codegen/typescript-operations": "1.17.14",
+    "@graphql-codegen/typescript-operations": "1.17.15",
     "@graphql-codegen/typescript-react-query": "^1.2.3",
     "@testing-library/react-hooks": "^5.1.0",
     "@types/jest": "^26.0.20",
diff --git a/yarn.lock b/yarn.lock
index 7f8fd35..5572c16 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -834,14 +834,14 @@
     lodash "~4.17.20"
     tslib "~2.1.0"
-"@graphql-codegen/typescript-operations@1.17.14":
-  version "1.17.14"
-  resolved "https://registry.yarnpkg.com/@graphql-codegen/typescript-operations/-/typescript-operations-1.17.14.tgz#69b4bee4d66f2ea7e288f1be889e08946ef3452a"
-  integrity sha512-jf1KnkA0i5hQNwc7bdMg5G6305DMSeTGDJSDoFryA2Tt9czWxY78m10/6GueUWo3zP6FIEhW1QRSve8ewTKEMg==
+"@graphql-codegen/typescript-operations@1.17.15":
+  version "1.17.15"
+  resolved "https://registry.yarnpkg.com/@graphql-codegen/typescript-operations/-/typescript-operations-1.17.15.tgz#c992e29ead1cf5c3f65dbbe1f522b09be30c36d6"
+  integrity sha512-HStWj3mUe+0ir2J0jqgjegrvcO1DIe2gzsoBBo9RHIYwyaxedUivxXvWY9XBfKpHv6sLa/ST1iYGeedrJELPtw==
   dependencies:
-    "@graphql-codegen/plugin-helpers" "^1.18.2"
-    "@graphql-codegen/typescript" "^1.20.1"
-    "@graphql-codegen/visitor-plugin-common" "^1.18.1"
+    "@graphql-codegen/plugin-helpers" "^1.18.3"
+    "@graphql-codegen/typescript" "^1.21.1"
+    "@graphql-codegen/visitor-plugin-common" "^1.19.0"
     auto-bind "~4.0.0"
     tslib "~2.1.0"
@@ -856,30 +856,14 @@
     change-case-all "^1.0.12"
     tslib "~2.1.0"
-"@graphql-codegen/typescript@^1.20.1":
-  version "1.21.0"
-  resolved "https://registry.yarnpkg.com/@graphql-codegen/typescript/-/typescript-1.21.0.tgz#301b1851cd278bedd1f49e1b3d654f4dc0af2943"
-  integrity sha512-23YttnZ+87dA/3lbCvPKdsrpEOx142dCT9xSh6XkSeyCvn+vUtETN2MhamCYB87G7Nu2EcLDFKDZjgXH73f4fg==
-  dependencies:
-    "@graphql-codegen/plugin-helpers" "^1.18.2"
-    "@graphql-codegen/visitor-plugin-common" "^1.18.3"
-    auto-bind "~4.0.0"
-    tslib "~2.1.0"
-
-"@graphql-codegen/visitor-plugin-common@^1.18.1", "@graphql-codegen/visitor-plugin-common@^1.18.3":
-  version "1.18.3"
-  resolved "https://registry.yarnpkg.com/@graphql-codegen/visitor-plugin-common/-/visitor-plugin-common-1.18.3.tgz#9d2c4449c3bdaffe3e782e2321fe0cb998b8a91d"
-  integrity sha512-6xJzt8hszCTKt3rTlcCURpuiAFuaiaZgStlVeRE1OrKEDiY1T3vwF3/7TonhfnEjqBWtZdMmXvNx3ArXkRUV4w==
+"@graphql-codegen/typescript@^1.21.1":
+  version "1.21.1"
+  resolved "https://registry.yarnpkg.com/@graphql-codegen/typescript/-/typescript-1.21.1.tgz#9bce3254b8ef30a6bf64e57ba3991f9be7a19b53"
+  integrity sha512-JF6Vsu5HSv3dAoS2ca3PFLUN0qVxotex/+BgWw/6SKhtd83MUPnzJ/RU3lACg4vuNTCWeQSeGvg8x5qrw9Go9w==
   dependencies:
-    "@graphql-codegen/plugin-helpers" "^1.18.2"
-    "@graphql-tools/optimize" "^1.0.1"
-    "@graphql-tools/relay-operation-optimizer" "^6"
-    array.prototype.flatmap "^1.2.4"
+    "@graphql-codegen/plugin-helpers" "^1.18.3"
+    "@graphql-codegen/visitor-plugin-common" "^1.19.0"
     auto-bind "~4.0.0"
-    dependency-graph "^0.10.0"
-    graphql-tag "^2.11.0"
-    parse-filepath "^1.0.2"
-    pascal-case "^3.1.1"
     tslib "~2.1.0"
 "@graphql-codegen/visitor-plugin-common@^1.19.0":
@@ -4382,11 +4366,6 @@ depd@~1.1.2:
   resolved "https://registry.yarnpkg.com/depd/-/depd-1.1.2.tgz#9bcd52e14c097763e749b274c4346ed2e560b5a9"
   integrity sha1-m81S4UwJd2PnSbJ0xDRu0uVgtak=
-dependency-graph@^0.10.0:
-  version "0.10.0"
-  resolved "https://registry.yarnpkg.com/dependency-graph/-/dependency-graph-0.10.0.tgz#dfebe384f1f36faf7782be203a7a71102a6335a6"
-  integrity sha512-c9amUgpgxSi1bE5/sbLwcs5diLD0ygCQYmhfM5H1s5VH1mCsYkcmAL3CcNdv4kdSw6JuMoHeDGzLgj/gAXdWVg==
-
 dependency-graph@^0.11.0:
   version "0.11.0"
   resolved "https://registry.yarnpkg.com/dependency-graph/-/dependency-graph-0.11.0.tgz#ac0ce7ed68a54da22165a85e97a01d53f5eb2e27"
```

**Comment by tschechniker** [comment]
Hi,

it "@graphql-codegen/visitor-plugin-common" which brakes with V 1.19.0. If you add this to you dep list it's working again:

"@graphql-codegen/visitor-plugin-common": "1.18.3",

**Comment by tkvlnk** [comment]
seems like the original issue caused by `change-case-all`

if you will explicitly lock it's version on `1.0.12` it will work fine

**Comment by aya-eiya** [comment]
@tschechniker @tkvlnk 

I thought the cause is `change-case-all` or `visitor-plugin-common` too, and I locked the versions of them but both fix did not work for me.

even if I don't upgrade the version,`yarn upgrade` causes the problem too.

here is the another module case I found .
```
"@graphql-codegen/typescript-react-query": "1.2.2",
```
will work, and
```
"@graphql-codegen/typescript-react-query": "1.2.3",
```
will not.
in this case, when revert the version, it works again.

my workaround: fix versions of the modules to be `1.17.14 ` and `1.2.2`, and not to run `yarn upgrade`.

**Comment by dotansimha** [comment]
I suspect it might happen due `visitor-plugin-common` - can you please try to make sure you are using the latest one? Can you please share the output of `yarn why @graphql-codegen/visitor-plugin-common` ? 

I suspect that the change of `change-case-all` in `visitor-plugin-common` might be related as well, since it can conflict if you have multiple/outdated versions of `visitor-plugin-common`.

**Comment by Demidea** [comment]
Same situation here... I also think that problem is in `visitor-plugin-common`

yarn why v1.22.10
warning ../../../package.json: No license field
[1/4] 🤔  Why do we have the module "@graphql-codegen/visitor-plugin-common"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@graphql-codegen/visitor-plugin-common@1.19.0"
info Reasons this module exists
   - "@graphql-codegen#typescript" depends on it
   - Hoisted from "@graphql-codegen#typescript#@graphql-codegen#visitor-plugin-common"
   - Hoisted from "@graphql-codegen#typescript-document-nodes#@graphql-codegen#visitor-plugin-common"
   - Hoisted from "@graphql-codegen#typescript-mongodb#@graphql-codegen#visitor-plugin-common"
   - Hoisted from "@graphql-codegen#typescript-operations#@graphql-codegen#visitor-plugin-common"
   - Hoisted from "@graphql-codegen#typescript-react-apollo#@graphql-codegen#visitor-plugin-common"
   - Hoisted from "@graphql-codegen#typescript-resolvers#@graphql-codegen#visitor-plugin-common"
info Disk size without dependencies: "1012KB"
info Disk size with unique dependencies: "2.05MB"
info Disk size with transitive dependencies: "44.32MB"
info Number of shared dependencies: 145
✨  Done in 3.85s.

**Comment by Everspace** [comment]
Codesandbox with the error: https://codesandbox.io/s/wispy-darkness-nxtp9

**Comment by vladislav-puzyrev** [comment]
Today, until about 8 o'clock GMT, I set up typescript type generation, but after an hour everything just stopped working, I didn't change the versions. I perform the steps from the README and this error is returned 😕

**Comment by ardatan** [comment]
We're aware of the issue and working on it.
Thanks for your patience.

**Comment by ardatan** [comment]
Could you all update all codegen packages to the latest version and try again?

**Comment by AhmedBHameed** [comment]
Work perfectly with the current versions. Thank you @ardatan 

```json
    "@graphql-codegen/cli": "1.21.3",
    "@graphql-codegen/introspection": "1.18.1",
    "@graphql-codegen/typescript": "1.21.1",
    "@graphql-codegen/typescript-operations": "1.17.15",
    "@graphql-codegen/typescript-react-apollo": "2.2.3",
```

**Comment by MaxHaider** [comment]
I sadly still experience the same issue.
`TypeError: func is not a function`

`  "devDependencies": {
    "@graphql-codegen/cli": "1.21.3",
    "@graphql-codegen/introspection": "1.18.1",
    "@graphql-codegen/typescript": "1.21.1",
    "@graphql-codegen/typescript-operations": "1.17.15",
    "@graphql-codegen/typescript-react-apollo": "2.2.3"
  }`

**Comment by ardatan** [comment]
@MaxHaider Could you run `yarn upgrade` and try again?

**Comment by pradyum98** [comment]
It worked ! Thanks a ton ! @ardatan

**Comment by MaxHaider** [comment]
@ardatan After running yarn upgrade, the error disappeared.
However now I get:

Plugin "typescript-react-apollo" requires extension to be ".ts" or ".tsx"!
    Error: Plugin "typescript-react-apollo" validation failed:
        at executePlugin (<path-to-project>/node_modules/@graphql-codegen/core/index.cjs.js:33:19)
        at async <path-to-project>/node_modules/@graphql-codegen/core/index.cjs.js:116:24
        at async Promise.all (index 2)
        at async Object.codegen (<path-to-project>/node_modules/@graphql-codegen/core/index.cjs.js:106:20)
        at async process (<path-to-project>/node_modules/@graphql-codegen/cli/bin.js:942:56)
        at async Promise.all (index 0)
        at async <path-to-project>/node_modules/@graphql-codegen/cli/bin.js:949:37
        at async Task.task (<path-to-project>/node_modules/@graphql-codegen/cli/bin.js:727:17)
    Error: Plugin "typescript-react-apollo" validation failed:
        at executePlugin (<path-to-project>/node_modules/@graphql-codegen/core/index.cjs.js:33:19)
        at async <path-to-project>/node_modules/@graphql-codegen/core/index.cjs.js:116:24
        at async Promise.all (index 2)
        at async Object.codegen (<path-to-project>/node_modules/@graphql-codegen/core/index.cjs.js:106:20)
        at async process (<path-to-project>/node_modules/@graphql-codegen/cli/bin.js:942:56)
        at async Promise.all (index 0)
        at async <path-to-project>/node_modules/@graphql-codegen/cli/bin.js:949:37
        at async Task.task (<path-to-project>/node_modules/@graphql-codegen/cli/bin.js:727:17)

**Comment by ardatan** [comment]
Could you share `codegen.yml` file? @MaxHaider

**Comment by MaxHaider** [comment]
I'm using a codegen.js file

```javascript
const dotenv = require('dotenv')

dotenv.config();

const apiSmartmeltsSchema = {
  [`${process.env.GRAPHQL_URL}`]: {},
}

const generateOptions = {
  plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
  config: {
    skipTypename: false,
    withHooks: true,
    withHOC: false,
    withComponent: false,
    apolloReactHooksImportFrom: "@apollo/client",
  },
}

module.exports = {
  overwrite: true,
  generates: {
    [`${process.env.GRAPHQL_URL}`]: {
      schema: apiSmartmeltsSchema,
      documents: ["./src/api/smartmelts-api/graphql/mutations/*.gql", "./src/api/smartmelts-api/graphql/queries/*.gql"],
      ...generateOptions,
    },
  },
}
```

**Comment by MaxHaider** [comment]
I'm using a codegen.js file

```javascript
const dotenv = require('dotenv')

dotenv.config();

const apiSchema = {
  [`${process.env.GRAPHQL_URL}`]: {},
}

const generateOptions = {
  plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
  config: {
    skipTypename: false,
    withHooks: true,
    withHOC: false,
    withComponent: false,
    apolloReactHooksImportFrom: "@apollo/client",
  },
}

module.exports = {
  overwrite: true,
  generates: {
    [`${process.env.GRAPHQL_URL}`]: {
      schema: apiSchema,
      documents: ["./src/api/graphql/mutations/*.gql", "./src/api/graphql/queries/*.gql"],
      ...generateOptions,
    },
  },
}
```

**Comment by ardatan** [comment]
Your configuration seems wrong.
```js
const dotenv = require('dotenv')

dotenv.config();

const apiSmartmeltsSchema = {
  [`${process.env.GRAPHQL_URL}`]: {},
}

const generateOptions = {
  plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
  config: {
    skipTypename: false,
    withHooks: true,
    withHOC: false,
    withComponent: false,
    apolloReactHooksImportFrom: "@apollo/client",
  },
}

module.exports = {
  overwrite: true,
  generates: {
    'output.tsx': { // This should be the name of the output file 
      schema: apiSmartmeltsSchema,
      documents: ["./src/api/smartmelts-api/graphql/mutations/*.gql", "./src/api/smartmelts-api/graphql/queries/*.gql"],
      ...generateOptions,
    },
  },
}
```

**Comment by MaxHaider** [comment]
@ardatan thank you so much, it worked!

I have a favor to ask, could you please delete this answer and repost it without my documents array changed to this: ["./src/api/graphql/mutations/*.gql", "./src/api/graphql/queries/*.gql"]?

I don't want the projectname to be public yet, thank you!

**Comment by ardatan** [comment]
Your configuration seems wrong. Under `generates`, we should have the output filenames
```js
const dotenv = require('dotenv')

dotenv.config();

const apiSchema= {
  [`${process.env.GRAPHQL_URL}`]: {},
}

const generateOptions = {
  plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
  config: {
    skipTypename: false,
    withHooks: true,
    withHOC: false,
    withComponent: false,
    apolloReactHooksImportFrom: "@apollo/client",
  },
}

module.exports = {
  overwrite: true,
  generates: {
    'output.tsx': { // This should be the name of the output file 
      schema: apiSchema,
      documents: ["./src/api/graphql/mutations/*.gql", "./src/api/graphql/queries/*.gql"],
      ...generateOptions,
    },
  },
}
```

Instead of using js file, I'd recommend to have YML file like below;
```yaml
schema: ${GRAPHQL_URL}
documents:
  - ./src/api/graphql/mutations/*.gql
  - ./src/api/graphql/queries/*.gql
generates:
  output.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      skipTypename: false
      withHooks: true
      withHOC: false
      withComponent: false
      apolloReactHooksImportFrom: "@apollo/client"
```

And you can run codegen with dotenv like this;
```
yarn graphql-codegen -r dotenv/config
```

**Comment by MaxHaider** [comment]
@ardatan thank you so much, you are the best!

**Comment by aya-eiya** [comment]
@ardatan It works perfectly too! thank you!
