### ISSUE TITLE
Nested fragments from files cause duplicate name error

### ISSUE THREAD

**Issue by defrex** [dotansimha/graphql-code-generator#3356]
If you have a fragment that includes a fragment (and both are from imported files), you get an error about a document being a duplicate. 1 level of nesting doesn't seem to trigger the issue.

Here is a minimal reproduction. All that's needed is the core `typescript` plugin to see the behavior.

https://codesandbox.io/s/cool-shape-v1cff

Here is the error text from the reproduction for reference.
```
    Not all operations have an unique name

    * UserQuery found in:

          - /sandbox/document.graphql
          - /sandbox/fragment1.graphql
    Error: Not all operations have an unique name: UserQuery
        at validateDuplicateDocuments (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:197:15)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:59:9)
        at process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:783:67)
        at Array.map (<anonymous>)
        at Listr.task.wrapTask (/sandbox/node_modules/@graphql-codegen/cli/bin.js:790:63)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ardatan** [comment]
Let's track the issue there;
https://github.com/dotansimha/graphql-code-generator/issues/3326
