### ISSUE TITLE
TypeError: func is not a function - npm

### ISSUE THREAD

**Issue by ozum** [dotansimha/graphql-code-generator#3360]
I was using `graphql-code-generator` successfully, but now when I run `npm run codegen`, I'm getting `func is not a function` error. As suggested in #3256, I removed `node_modules`, `package-lock.json` and `npm install` from scratch, but it didn't help.

I added a sandbox with same dependencies here: https://codesandbox.io/s/silly-haibt-3u7sq

Unfortunately, I cannot reproduce error there. Please advise.

```
✖ types/types.ts
    TypeError: func is not a function
        at .../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:19
```

Error message points to `convertNameParts` function:

```js
function convertNameParts(str, func, removeUnderscore = false) {
    if (removeUnderscore) {
        return func(str);
    }
    return str
        .split('_')
        .map(s => func(s))
        .join('_');
}
```

<details><summary>Please click to see full error message</summary>

```
TypeError: func is not a function
        at .../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:19
        at Array.map (<anonymous>)
        at convertNameParts (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:10)
        at opts (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:425:24)
        at Object.convert (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:462:43)
        at TsVisitor.convertName (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:488:78)
        at TsVisitor._getTypeForNode (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:889:21)
        at TsVisitor.NamedType (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:892:21)
        at TsVisitor.NamedType (.../node_modules/@graphql-codegen/typescript/index.cjs.js:101:31)
        at Object.visit (.../node_modules/graphql/language/visitor.js:242:26)
        at Object.plugin (.../node_modules/@graphql-codegen/typescript/index.cjs.js:195:35)
        at executePlugin (.../node_modules/@graphql-codegen/core/index.cjs.js:50:41)
        at .../node_modules/@graphql-codegen/core/index.cjs.js:106:30
        at Array.map (<anonymous>)
        at Object.codegen (.../node_modules/@graphql-codegen/core/index.cjs.js:96:54)
        at process (.../node_modules/@graphql-codegen/cli/bin.js:783:67)
    TypeError: func is not a function
        at .../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:19
        at Array.map (<anonymous>)
        at convertNameParts (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:259:10)
        at opts (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:425:24)
        at Object.convert (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:462:43)
        at TsVisitor.convertName (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:488:78)
        at TsVisitor._getTypeForNode (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:889:21)
        at TsVisitor.NamedType (.../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:892:21)
        at TsVisitor.NamedType (.../node_modules/@graphql-codegen/typescript/index.cjs.js:101:31)
        at Object.visit (.../node_modules/graphql/language/visitor.js:242:26)
        at Object.plugin (.../node_modules/@graphql-codegen/typescript/index.cjs.js:195:35)
        at executePlugin (.../node_modules/@graphql-codegen/core/index.cjs.js:50:41)
        at .../node_modules/@graphql-codegen/core/index.cjs.js:106:30
        at Array.map (<anonymous>)
        at Object.codegen (.../node_modules/@graphql-codegen/core/index.cjs.js:96:54)
        at process (.../node_modules/@graphql-codegen/cli/bin.js:783:67)
```

</details>

Thanks,

**Comment by ardatan** [comment]
In codesandbox, I removed `^` from codegen versions to have stable versioning so it worked.
https://codesandbox.io/s/peaceful-clarke-ifo4j

**Comment by ozum** [comment]
@ardatan thank you for the response. I completely agree, but I cannot reproduce it in codesandbox similar to #3256, but I get it again and again even installing from scratch.

node: 13.6.0
npm: 6.13.4
MacOS: 10.14.6

Other versions are as described in `package.json`

In case you need, I added `tsconfig.json` to sandbox.

**Comment by jcharlesworthuk** [comment]
I had this same issue with the very latest version 1.11.2

[This comment](https://github.com/dotansimha/graphql-code-generator/issues/3256#issuecomment-574265086) fixed it for me, so maybe that's something to look into

`npm i -D change-case`

**Comment by ardatan** [comment]
Could you try with the exact canary version? (Without ^ mark)
`1.11.3-alpha-21386b4a.87+21386b4a`

**Comment by ozum** [comment]
Using below I'm getting same error with "npm install" from scratch. (yarn is still OK)

```json
{
  "@graphql-codegen/cli": "1.11.3-alpha-21386b4a.87",
  "@graphql-codegen/typescript": "1.11.3-alpha-21386b4a.87",
  "@graphql-codegen/typescript-graphql-files-modules": "1.11.3-alpha-21386b4a.87",
  "@graphql-codegen/typescript-operations": "1.11.3-alpha-21386b4a.87"
}
```

**Comment by ardatan** [comment]
Does this version work for you?
`1.11.3-alpha-428b4ff4.92`

**Comment by ozum** [comment]
@ardatan still same error using `1.11.3-alpha-33d6634e.92`

**Comment by dotansimha** [comment]
@ozum can you please create a reproduction in a repo/sandbox?

**Comment by ozum** [comment]
Hi @dotansimha and @ardatan, thank you for the responses.

I finally found a way to reproduce the error:

1. Goto sandbox in first post (https://codesandbox.io/s/silly-haibt-3u7sq).
1. Open a terminal in sandbox.
1. Delete files: `rm -rf node_modules/ package-lock.json`
1. Install using npm with empty cache: `npm install --cache /tmp/empty-cache`
1. You should get error shown in below sandbox screenshot:

![image](https://user-images.githubusercontent.com/1497060/73256865-c78c7f80-41d3-11ea-984c-d28dce456151.png)

Thanks,

**Comment by ardatan** [comment]
I tried by following your steps and installing this canary version. It worked with no errors;
`1.11.3-alpha-395be8af.104+395be8af`
https://codesandbox.io/embed/elastic-faraday-qz3bh?fontsize=14&hidenavigation=1&theme=dark

**Comment by ozum** [comment]
@ardatan, I updated the sandbox and problem seems to be solved. Case may be closed. Thanks.

**Comment by dotansimha** [comment]
Fixed in `v1.12.0`

**Comment by ValterSantosMatos** [comment]
Still happening with:

```
    "@graphql-codegen/cli": "1.21.2",
    "@graphql-codegen/typescript": "1.21.1",
    "@graphql-codegen/typescript-operations": "1.17.15",
    ```

**Comment by ardatan** [comment]
Could you please create an issue with a reproduction on CodeSandbox? Thanks!
