### ISSUE TITLE
TypeError: pascalCase.pascalCase is not a function

### ISSUE THREAD

**Issue by Thomb89** [dotansimha/graphql-code-generator#3387]
I just built my first graphql-api and decied to use `graphql-code-generator` with `version 1.11.2`. 

When converting the schema to typescript, i always received the error `pascalCase.pascalCase is not a function`.

When looking at the [visitor-plugin-common](https://github.com/dotansimha/graphql-code-generator/tree/master/packages/plugins/other/visitor-plugin-common) in the file [base-document-visitor.ts](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts) (line 171) pascalCase is used as a function (the same can be seen in [naming.ts](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/other/visitor-plugin-common/src/naming.ts) [lines 63, 91]).

When i download the [npm-package](https://registry.npmjs.org/@graphql-codegen/visitor-plugin-common/-/visitor-plugin-common-1.11.2.tgz) and look into the `index.cjs.js` the function is converted to an object method (lines 425, 448, 981, 1759) `pascalCase.pascalCase` which leads to the following output: 

`TypeError: pascalCase.pascalCase is not a function
        at TypeScriptDocumentsVisitor.OperationDefinition (../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:982:136)
        at Object.visit (../node_modules/graphql/
language/visitor.js:242:26)
        at Object.plugin (../node_modules/@graphq
l-codegen/typescript-operations/index.cjs.js:114:35)
        at executePlugin (../node_modules/@graphq
l-codegen/core/index.cjs.js:50:41)
        at ../node_modules/@graphql-codegen/core/
index.cjs.js:106:30
        at Array.map (<anonymous>)
        at Object.codegen (../node_modules/@graph
ql-codegen/core/index.cjs.js:96:54)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async process (../node_modules/@graphq
l-codegen/cli/bin.js:783:56)
        at async Promise.all (index 0)
        at async ../node_modules/@graphql-codegen
/cli/bin.js:790:37
        at async Task.task (../node_modules/@grap
hql-codegen/cli/bin.js:582:17)
    TypeError: pascalCase.pascalCase is not a function
        at TypeScriptDocumentsVisitor.OperationDefinition (../node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js:982:136)
        at Object.visit (../node_modules/graphql/
language/visitor.js:242:26)
        at Object.plugin (../node_modules/@graphq
l-codegen/typescript-operations/index.cjs.js:114:35)
        at executePlugin (../node_modules/@graphq
l-codegen/core/index.cjs.js:50:41)
        at ../node_modules/@graphql-codegen/core/
index.cjs.js:106:30
        at Array.map (<anonymous>)
        at Object.codegen (../node_modules/@graph
ql-codegen/core/index.cjs.js:96:54)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async process (../node_modules/@graphq
l-codegen/cli/bin.js:783:56)
        at async Promise.all (index 0)
        at async ../node_modules/@graphql-codegen
/cli/bin.js:790:37
        at async Task.task (../node_modules/@grap
hql-codegen/cli/bin.js:582:17)`

**Comment by ardatan** [comment]
`1.11.3-alpha-428b4ff4.92`
Could you try with this canary version?

**Comment by Thomb89** [comment]
works like a charm with version `1.11.3-alpha-33d6634e.92`.
Thanks for the fast response!

**Comment by ardatan** [comment]
Awesome! Let's keep it open until we release a new stable version.

**Comment by dotansimha** [comment]
Fixed in `v1.12.0`
