### ISSUE TITLE
Error reporting is confusing

### ISSUE THREAD

**Issue by fetis** [dotansimha/graphql-code-generator#3664]
Hello,

I'm migrating from version 0.18 to v1.0 and got an error

> GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.

The problem is that I get this error for _every file_ (~60 files) which in my document list. So it looks like the error is triggered on one of the documents and then just repeated for every next file whenever it has problems or not.

**Comment by ardatan** [comment]
@fetis We need a clear reproduction to help you better.

**Comment by fetis** [comment]
@ardatan below is the output on the truncated set of files.

as you can see it shows error on every file, where actual source of error is only `case-link-fields.ts` file
```
[16:00:49] Parse configuration [started]
[16:00:49] Parse configuration [completed]
[16:00:49] Generate outputs [started]
[16:00:49] Generate ./src/app/graphql/models/types.ts [started]
[16:00:49] Load GraphQL schemas [started]
[16:00:50] Load GraphQL schemas [completed]
[16:00:50] Load GraphQL documents [started]
[16:00:50] Load GraphQL documents [completed]
[16:00:50] Generate [started]
[16:00:50] Generate [failed]
[16:00:50] →
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:5:5
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:25:5
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:14:5
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/author-fields.ts:5:5
        at ./src/app/graphql/fragments/author-fields.ts:25:5
        at ./src/app/graphql/fragments/author-fields.ts:14:5
        at ./src/app/graphql/fragments/author-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/case-link-fields.ts:5:5
        at ./src/app/graphql/fragments/case-link-fields.ts:25:5
        at ./src/app/graphql/fragments/case-link-fields.ts:14:5
        at ./src/app/graphql/fragments/case-link-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/case-state-fields.ts:5:5
        at ./src/app/graphql/fragments/case-state-fields.ts:25:5
        at ./src/app/graphql/fragments/case-state-fields.ts:14:5
        at ./src/app/graphql/fragments/case-state-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/overdue.ts:5:5
        at ./src/app/graphql/fragments/overdue.ts:25:5
        at ./src/app/graphql/fragments/overdue.ts:14:5
        at ./src/app/graphql/fragments/overdue.ts:37:5
[16:00:50] Generate ./src/app/graphql/models/types.ts [failed]
[16:00:50] →
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:5:5
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:25:5
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:14:5
        at ./src/app/graphql/fragments/admin-case-list-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/author-fields.ts:5:5
        at ./src/app/graphql/fragments/author-fields.ts:25:5
        at ./src/app/graphql/fragments/author-fields.ts:14:5
        at ./src/app/graphql/fragments/author-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/case-link-fields.ts:5:5
        at ./src/app/graphql/fragments/case-link-fields.ts:25:5
        at ./src/app/graphql/fragments/case-link-fields.ts:14:5
        at ./src/app/graphql/fragments/case-link-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/case-state-fields.ts:5:5
        at ./src/app/graphql/fragments/case-state-fields.ts:25:5
        at ./src/app/graphql/fragments/case-state-fields.ts:14:5
        at ./src/app/graphql/fragments/case-state-fields.ts:37:5
    GraphQLDocumentError: Fields "state" conflict because subfields "reason" conflict because they return conflicting types WaitingReason! and WaitingReason. Use different aliases on the fields to fetch both if this was intentional.
        at ./src/app/graphql/fragments/overdue.ts:5:5
        at ./src/app/graphql/fragments/overdue.ts:25:5
        at ./src/app/graphql/fragments/overdue.ts:14:5
        at ./src/app/graphql/fragments/overdue.ts:37:5
[16:00:50] Generate outputs [failed]
Something went wrong
```

**Comment by ardatan** [comment]
@fetis Those logs are not helpful without a reproduction. We need a clear reproduction as a codesandbox project or a repository.

**Comment by fetis** [comment]
@ardatan I understand, but I need some time to extract it from a private repo, which I obviously can't share

**Comment by fetis** [comment]
@ardatan I made a demo repo https://github.com/fetis/gqlgen-error with the same error as I have on production code, but I was not able to reproduce exactly the same error reporting as I mentioned. Maybe it depends on the number of files?

In this demo repo, I correctly get an error about  `_problem-query.ts` file, but in my real project repo this error points to the at _the file at the end of the list_, not the file where the problem was triggered 

I have 60 query files in a real project, any ideas about how we can reproduce it with a fewer amount?

**Comment by dotansimha** [comment]
This was fixed a long time ago. 
@fetis please use latest version and re-open if it's the issue still persists.
