### ISSUE TITLE
Error: Unknown argument: config

### ISSUE THREAD

**Issue by suhailbinnisar** [dotansimha/graphql-code-generator#3668]
When i execute
```graphql-codegen --config ./admin.codegen.yml```

It throws this error:
```javascript
Error: Unknown argument: config
    at Array.<anonymous> (/usr/lib/node_modules/graphql-codegen/lib/cli.js:142:31)
    at Object.self.fail (/usr/lib/node_modules/graphql-codegen/node_modules/yargs/lib/usage.js:35:17)
    at Object.self.unknownArguments (/usr/lib/node_modules/graphql-codegen/node_modules/yargs/lib/validation.js:139:13)
    at parseArgs (/usr/lib/node_modules/graphql-codegen/node_modules/yargs/yargs.js:811:32)
    at Object.get [as argv] (/usr/lib/node_modules/graphql-codegen/node_modules/yargs/yargs.js:668:16)
    at Object.<anonymous> (/usr/lib/node_modules/graphql-codegen/lib/cli.js:143:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```

same error when running via **yarn script**

**script**
```
    "admin:generate:types": "graphql-codegen --config ./admin.codegen.yml"
```

I have tried shorthand argument **-c** too

**Comment by suhailbinnisar** [comment]
oops I forgot to add typescript as a dev dependency to root packages.json as I was using monorepo
