### ISSUE TITLE
`Unable to find field "__type" on type "Query"` with presets `import-types` and `near-operation-file`

### ISSUE THREAD

**Issue by phryneas** [dotansimha/graphql-code-generator#3863]
**Describe the bug**

When I have a query against `Query.__type()` in combination with `import-types` or `near-operation`, graphql-codegen fails:

```
 yarn run v1.22.0
$ yarn gql:download && yarn gql:generate
$ get-graphql-schema http://127.0.0.1:8000 > src/graphql/schema.graphql
$ yarn gql:codegen
$ graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ✔ Generate src/graphql/graphql-types.tsx
    ❯ Generate to src/graphql/graphql-operations.tsx (using EXPERIMENTAL preset "
import-types")
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to find field "__type" on type "Query"!
    ✔ Generate src/graphql/fragment-introspection.ts


 Found 1 error

  ✖ src/graphql/graphql-operations.tsx
    Error: Unable to find field "__type" on type "Query"!
        at nextTypeName (/base/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:141:39)
        at Object.enter (/base/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:160:23)
        at Object.visit (/base/node_modules/graphql/language/visitor.js:242:26)
        at Object.isUsingTypes (/base/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:121:13)
        at options.documents.map.documentFile (/base/node_modules/@graphql-codegen/import-types-preset/index.cjs.js:30:31)
        at Array.map (<anonymous>)
        at Object.buildGeneratesSection (/base/node_modules/@graphql-codegen/import-types-preset/index.cjs.js:29:27)
        at Listr.task.wrapTask (/base/node_modules/@graphql-codegen/cli/bin.js:799:64)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    Error: Unable to find field "__type" on type "Query"!
        at nextTypeName (/base/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:141:39)
        at Object.enter (/base/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:160:23)
        at Object.visit (/base/node_modules/graphql/language/visitor.js:242:26)
        at Object.isUsingTypes (/base/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:121:13)
        at options.documents.map.documentFile (/base/node_modules/@graphql-codegen/import-types-preset/index.cjs.js:30:31)
        at Array.map (<anonymous>)
        at Object.buildGeneratesSection (/base/node_modules/@graphql-codegen/import-types-preset/index.cjs.js:29:27)
        at Listr.task.wrapTask (/base/node_modules/@graphql-codegen/cli/bin.js:799:64)
        at process._tickCallback (internal/process/next_tick.js:68:7)


Something went wrong
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1]    12898 exit 1     yarn gql

```

**To Reproduce**

When I dump everything into one target file with plugins
```
- typescript
- typescript-operations
- typescript-react-apollo
```
I get no error, but once I split it up into multiple files & change the preset to either `import-types` or `near-operation-file`, I get the error message
> Unable to find field "__type" on type "Query"

True, that field is not explicitly part of my `Query` type in the schema, but it should be there implicitly for every schema.

It seems that these implicit fields are not available from the presets?

Use a query like 
```ts
export const GetFilterInfo = gql`
    query FilterInfo($filterName: String!) {
        __type(name: $filterName) {
            kind
            name
            description
            inputFields {
                name
                type {
                    kind
                    name
                }
            }
        }
    }
`;
```

with the presets `import-types` or `near-operation-file`.

**Expected behavior**

No error message, files get generated.

**Environment:**

- OS: Linux
- `@graphql-codegen/^1.13.2`: 
- NodeJS: 10.17.0

**Comment by gfviegas** [comment]
Any update? Still experiencing the same issue

**Comment by Urigo** [comment]
Hi @phryneas and @gfviegas and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 0`.

Now in order to advance to `stage 1` we'll need a simple reproduction, maybe in code-sandbox? 

Later to progress to `stage 2`, a failing test would be needed, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by lmatheus** [comment]
@Urigo @dotansimha  I believe this might be able to serve as a reproduction:

https://github.com/lmatheus/codegen-apollo-repro

Please let me know if this requires any further details. Thanks!

**Comment by Urigo** [comment]
Thank you @lmatheus! 

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 1` thanks to your reproduction! Thank you for that!

Now in order to advance to `stage 2` we'll need a failing test, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by wiktorsikora** [comment]
Any progress on this?

**Comment by Grohden** [comment]
Here's a patch for those who stumbled across this issue:
```diff
diff --git a/cjs/helpers.js b/cjs/helpers.js
index 7bb51e2195a7c8687c51ebda46b66e2fdf953d2c..887ed69e6806d8e61b5e0e7ce62dc5f8f321b6ea 100644
--- a/cjs/helpers.js
+++ b/cjs/helpers.js
@@ -81,6 +81,9 @@ function isUsingTypes(document, externalFragments, schema) {
                                 throw new Error(`Unable to find parent type! Please make sure you operation passes validation`);
                             }
                             const field = lastType.getFields()[parent.name.value];
+                            if(parent.name.value === '__type') {
+                                return '__Type';
+                            }
                             if (!field) {
                                 throw new Error(`Unable to find field "${parent.name.value}" on type "${lastType}"!`);
                             }

```
(I don't expect this to work in every case - like `__schema` - and this is definitely not the general solution )

Also, if anyone wants to test this here's a **prototype** case (`packages/utils/plugins-helpers/tests/is-using-types.spec.ts`):

```typescript
    it.only('#3863 - error on __type selections', () => {
      const schema = buildSchema(/* GraphQL */ `
        enum YearsOfExperience {
          "Five Years Plus"
          five_years_plus
        }

        type Query {
          foo: YearsOfExperience
        }
      `)
      const ast = parse(/* GraphQL */ `
        query AllRequests {
          yearsOfExperience: __type(name: "YearsOfExperience") {
            enumValues {
              name
              description
            }
          }
        }
      `);

      expect(isUsingTypes(ast, [], schema)).toBeTruthy();
    })
 ```
---
On a side note: why is it so hard to test a single package? I've downloaded this repo and saw no instructions on how to test the `plugins-helper` package, and once I was able to run the tests (I had to build the package - no instructions given) the jest runner ran every test and not only the ones at the package folder, it's hard to even want to contribute if it's not accessible to write and run a **single** test

**Comment by ardatan** [comment]
Sorry for your bad experience but actually we have a contributor guide linked in README;
https://github.com/dotansimha/graphql-code-generator#contributing

**Comment by Grohden** [comment]
Oh, my bad then, only saw the workflow guide
