### ISSUE TITLE
MongoDB plugin doesn't work with federation

### ISSUE THREAD

**Issue by lgandecki** [dotansimha/graphql-code-generator#4290]
**Describe the bug**
MongoDB plugin doesn't work with federation

**To Reproduce**

https://codesandbox.io/s/quirky-brook-i12hs

yarn && yarn generate

produces errors like below. if I remove the  `- typescript-mongodb` part from the codegen.yml the types are correctly generated.:
```
 Error: Unknown directive "@key".

    Unknown directive "@external".

    Unknown directive "@external".

    Unknown directive "@external".

    Unknown directive "@requires".
        at assertValidSDL (/sandbox/node_modules/graphql/validation/validate.js:107:11)
        at Object.buildASTSchema (/sandbox/node_modules/graphql/utilities/buildASTSchema.js:45:34)
        at makeSchema (/sandbox/node_modules/@graphql-tools/merge/index.cjs.js:917:99)
        at Object.mergeSchemas (/sandbox/node_modules/@graphql-tools/merge/index.cjs.js:900:12)
        at pluginPackages.reduce (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:65:22)
        at Array.reduce (<anonymous>)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:60:36)
        at process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:845:67)
        at Array.map (<anonymous>)
        at Listr.task.wrapTask (/sandbox/node_modules/@graphql-codegen/cli/bin.js:852:63)
    Error: Unknown directive "@key".

    Unknown directive "@external".

    Unknown directive "@external".

    Unknown directive "@external".

    Unknown directive "@requires".
        at assertValidSDL (/sandbox/node_modules/graphql/validation/validate.js:107:11)
        at Object.buildASTSchema (/sandbox/node_modules/graphql/utilities/buildASTSchema.js:45:34)
        at makeSchema (/sandbox/node_modules/@graphql-tools/merge/index.cjs.js:917:99)
        at Object.mergeSchemas (/sandbox/node_modules/@graphql-tools/merge/index.cjs.js:900:12)
        at pluginPackages.reduce (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:65:22)
        at Array.reduce (<anonymous>)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:60:36)
        at process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:845:67)
        at Array.map (<anonymous>)
        at Listr.task.wrapTask (/sandbox/node_modules/@graphql-codegen/cli/bin.js:852:63)
```

Is this problematic to make work? This is not a high priority for us, as we normally wouldn't use federation with graphql, but still curious, maybe it's an easy fix?

Thanks!

**Comment by dotansimha** [comment]
If you just need to make it work with those directives, create a separate file with the declaration of it, and let codegen know about it. 
You can find it here: https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#federation-schema-specification
