### ISSUE TITLE
Doesn't work with federated schema

### ISSUE THREAD

**Issue by yuhanz** [dotansimha/graphql-code-generator#4450]
Try this schema with graphql federation:
https://github.com/apollographql/federation-jvm/blob/master/spring-example/src/main/resources/schemas/inventory.graphql

`graphql-inspector diff /tmp/inventory.graphql /tmp/inventory.graphql`

This resulted in the following error:
```
error Error: Unknown directive "@key".

Unknown directive "@extends".

Unknown directive "@external".
    at assertValidSDL (/usr/local/lib/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/usr/local/lib/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/merge/index.cjs.js:954:99)
    at Object.mergeSchemasAsync (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/merge/index.cjs.js:945:12)
    at async Object.loadSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.cjs.js:650:20)
Error: Unknown directive "@key".

Unknown directive "@extends".

Unknown directive "@external".
    at assertValidSDL (/usr/local/lib/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/usr/local/lib/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/merge/index.cjs.js:954:99)
    at Object.mergeSchemasAsync (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/merge/index.cjs.js:945:12)
    at async Object.loadSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.cjs.js:650:20)
```

graphq-inspector version 2.1.0

**Comment by ardatan** [comment]
How is that related to GraphQL Code Generator?

**Comment by yuhanz** [comment]
sorry.. I posted at the wrong project.
