### ISSUE TITLE
AggregateError when query param name same with the directive param

### ISSUE THREAD

**Issue by xiaoliu-heng** [dotansimha/graphql-code-generator#4654]
**Describe the bug**
 
AggregateError when query param name same with the directive

**To Reproduce**
write client schema like and generate
```graphql
query registrations($filter: RegistrationFilterInput, $page: PageInfo) {
  registrations(filter: $filter, page: $page) @connection(key: "registrations", filter: ["filter"]) {
    items {
      # ...
    }
    pageIndex
  }
}
```

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type RegistrationPage implements Pageable {
  items: [Registration!]
  pageSize: Int!
  pageIndex: Int!
  total: Int!
}

type Query {
  registrations(filter: RegistrationFilterInput, pageInfo: PageInfo): RegistrationPage
}

```

2. My GraphQL operations:

```graphql
registrations(filter: $filter, pageInfo: $pageInfo) @connection(key: "registrations", filter: ["filter"]){
        items {
            ...RegistrationFields
        }
        pageIndex
        pageSize
        total
    }
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "server.graphql"
documents: ["src/**/*.ts", "src/**/*.graphql"]
generates:
  src/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-document-nodes"
    config:
      avoidOptionals: false
      exportFragmentSpreadSubTypes: true
      enumsAsTypes: false

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
export the documents with the directive

**Environment:**

- OS: MacOS 10.15.6
- `@graphql-codegen/...`: 
- NodeJS: 12.13.1

**Additional context**
<!-- Add any other context about the problem here. -->
```sh
> graphql-codegen --config codegen.yml --clientSchema clientDirective.graphql

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/graphql.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →         at /Users/xiaoliu/workspace/frontend-main/src/components/registration/RegistrationHooks/registration.query.graphql:7:137


 Found 1 error

  ✖ src/graphql.ts
    AggregateError: 
        GraphQLDocumentError: Expected type RegistrationFilterInput, found ["filter"].
            at /Users/xiaoliu/workspace/frontend-main/src/components/registration/RegistrationHooks/registration.query.graphql:7:137
        at Object.checkValidationErrors (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-toolkit/common/index.cjs.js:431:15)
        at Object.codegen (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/core/index.cjs.js:89:16)
        at async process (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/cli/bin.js:764:56)
        at async Promise.all (index 0)
        at async /Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/cli/bin.js:771:37
        at async Task.task (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/cli/bin.js:567:17)
    AggregateError: 
        GraphQLDocumentError: Expected type RegistrationFilterInput, found ["filter"].
            at /Users/xiaoliu/workspace/frontend-main/src/components/registration/RegistrationHooks/registration.query.graphql:7:137
        at Object.checkValidationErrors (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-toolkit/common/index.cjs.js:431:15)
        at Object.codegen (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/core/index.cjs.js:89:16)
        at async process (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/cli/bin.js:764:56)
        at async Promise.all (index 0)
        at async /Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/cli/bin.js:771:37
        at async Task.task (/Users/xiaoliu/workspace/frontend-main/node_modules/@graphql-codegen/cli/bin.js:567:17)


```

**Comment by dotansimha** [comment]
Hi @xiaoliu-heng , 
Can you please share a live reproduction? We need to have a real, working environment with this issue, please make sure to use latest versions, since it seems like some deps are outdated in the callstack you shared.
I'm not sure it's something related to codegen, because the error seems like a graphql error, coming from graphql-js itself.

**Comment by osalama7** [comment]
Hi, I'm experiencing a similar issue, @xiaoliu-heng do you have any updates on reproducing it?

**Comment by nodkz** [comment]
To solve this problem just add the following line to your `schema.graphql` file:

```graphql
directive @connection(key: String! filter: [String!]) on FIELD
```

@dotansimha I didn't find where graphql-codegen adds the wrong `@connection` directive definition for making a PR. 

BTW It will be nice if this directive will be added to the `react-apollo` plugin.

**Comment by xiaoliu-heng** [comment]
@dotansimha @osalama7 sorry I'm late. <a href="https://codesandbox.io/s/eager-night-c0rq3?file=/codegen.yml">Codesandbox</a>
to reproduce, just remove the `directive.graphql`

@nodkz It works. thanks!

**Comment by dotansimha** [comment]
> To solve this problem just add the following line to your `schema.graphql` file:
> 
> ```graphql
> directive @connection(key: String!, filter: [String!]) on FIELD
> ```
> 
> @dotansimha I didn't find where graphql-codegen adds the wrong `@connection` directive definition for making a PR.
> 
> BTW It will be nice if this directive will be added to the `react-apollo` plugin.

Actually, we are not adding that at all. Codegen doesn't do any schema/operations manipulations, so I can only assume this directive comes from somewhere within @xiaoliu-heng 's code. 

As I said, this error is coming directly from `graphql-js`, and I'm not sure there is something we can do about it.

**Comment by briareus-the-titan** [comment]
is there a solution to this yet?
