### ISSUE TITLE
typescript-type-graphql does not appropriately handle non-string descriptions

### ISSUE THREAD

**Issue by jakelauer** [dotansimha/graphql-code-generator#5497]
**Describe the bug**
The GraphQL schema I'm using has some description fields that resolve to objects when parsed to `GraphQLSchema`. These are not appropriately handled by the `typescript-type-graphql` plugin, which attempts to pass the description object to an string escape function.

**To Reproduce**

I have set up a repro using this sandbox:
https://codesandbox.io/s/beautiful-dew-5i4tm

Note: This uses a JSON introspection schema. You should notice that, when `yarn generate` is run, you will encounter the following error:

  ✖ graphql.ts
    TypeError: str.replace is not a function

This is because the value being passed to the `escapeString` function is as follows:
```
{ 
  kind: 'StringValue',
  value:'If the asset doesn\'t exist in the queried locale, setting it to true would return the asset published in the fallback locale (if it is published in the fallback locale)',
  block: true,
  loc: { start: 74, end: 258 } 
}
```

Here is the stack trace:

```
Found 1 error

  ✖ graphql.ts
    TypeError: str.replace is not a function
        at escapeString (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:19:22)
        at TypeGraphQLVisitor.getDecoratorOptions (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:89:44)
        at TypeGraphQLVisitor.InputValueDefinition (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:278:39)
        at visitorPluginCommon.DeclarationBlock.export.asKind.withName.withComment.withBlock.field.arguments.map.argument (/sandbox/node
_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:163:61)
        at Array.map (<anonymous>)
        at TypeGraphQLVisitor.getArgumentsObjectDeclarationBlock (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.c
js.js:163:40)
        at TypeGraphQLVisitor.getArgumentsObjectTypeDefinition (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs
.js:167:37)
        at fieldsWithArguments.map.field (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:112:29)
        at Array.map (<anonymous>)
        at TypeGraphQLVisitor.buildArgumentsBlock (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:103:14)
        at TypeGraphQLVisitor.ObjectTypeDefinition (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:144:47)
        at Object.visit (/sandbox/node_modules/graphql/language/visitor.js:243:26)
        at Object.plugin (/sandbox/node_modules/@graphql-codegen/typescript-type-graphql/index.cjs.js:322:35)
        at executePlugin (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:36:35)
        at Promise.all.options.plugins.map (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:113:30)
        at Array.map (<anonymous>)
```

#############
#############
-->

1. My GraphQL schema:

[schema.zip](https://github.com/dotansimha/graphql-code-generator/files/5929365/schema.zip)

2. My GraphQL operations:

I don't know what this is :(

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: schema.json
generates:
  graphql.ts:
    plugins:
      - "typescript-type-graphql"
```

**Expected behavior**

The code is generated without issue

**Environment:**

- OS: Windows 10
    "@graphql-codegen/cli": "1.20.1",
    "@graphql-codegen/introspection": "1.18.1",
    "@graphql-codegen/typescript": "1.20.2",
    "@graphql-codegen/typescript-type-graphql": "^1.18.2"
- NodeJS: 12

**Additional context**

**Comment by dotansimha** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/commit/febe054a1fcad107579b860c6a9c22eb5d2aef09

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-type-graphql@1.18.3`
