### ISSUE TITLE
documentation-ask: How do I run this ?

### ISSUE THREAD

**Issue by nojvek** [dotansimha/graphql-code-generator#6126]
`npx graphql-codegen init` returns an error

```
Error: Unknown argument: init
    at Array.<anonymous> (/Users/noj/.npm/_npx/81b0be6240671404/node_modules/graphql-codegen/lib/cli.js:142:31)
    at Object.self.fail (/Users/noj/.npm/_npx/81b0be6240671404/node_modules/yargs/lib/usage.js:35:17)
    at Object.self.unknownArguments (/Users/noj/.npm/_npx/81b0be6240671404/node_modules/yargs/lib/validation.js:139:13)
    at parseArgs (/Users/noj/.npm/_npx/81b0be6240671404/node_modules/yargs/yargs.js:811:32)
    at Object.get [as argv] (/Users/noj/.npm/_npx/81b0be6240671404/node_modules/yargs/yargs.js:668:16)
    at Object.<anonymous> (/Users/noj/.npm/_npx/81b0be6240671404/node_modules/graphql-codegen/lib/cli.js:143:19)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)

```

Documentation probably needs to be clear on how to run this without config. I have my schema.gql, and a bunch of typescript files with

```
const {data, loading, error} = useQuery<FIXME>(gql`query {...}`)
```

How do I get the generator to generate the FIXME types?

**Comment by dotansimha** [comment]
Codegen can't run without a config file. It must have a schema and plugins list. You can find the complete docs here: https://www.graphql-code-generator.com/docs/getting-started/installation 

I think some version of npx doesn't support passing arguments list that, and you must do `npx graphql-codegen -- init`. 

Regrading FIXME, not sure what do you mean, if that's a question - please refer to GitHub Discussions, and if it's a bug, please report an issue with a reproduction.
