### ISSUE TITLE
Swallowed Errors  | AggregateError: GraphQL Document Validation failed

### ISSUE THREAD

**Issue by pmazumder3927** [dotansimha/graphql-code-generator#6463]
**Describe the bug**
When running codegen on a document where a field doesn't exist, a very nonspecific error is emitted
```
 Found 2 errors

  ✖ ./graphql.schema.json
    AggregateError: GraphQL Document Validation failed with 1 errors
        at new exports.AggregateError (/sandbox/node_modules/@graphql-tools/utils/index.js:898:16)
        at Object.checkValidationErrors (/sandbox/node_modules/@graphql-tools/utils/index.js:960:15)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:102:15)
        at async process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:992:56)
        at async Promise.all (index 0)
        at async /sandbox/node_modules/@graphql-codegen/cli/bin.js:999:37
        at async Task.task (/sandbox/node_modules/@graphql-codegen/cli/bin.js:778:17)
    AggregateError: GraphQL Document Validation failed with 1 errors
        at new exports.AggregateError (/sandbox/node_modules/@graphql-tools/utils/index.js:898:16)
        at Object.checkValidationErrors (/sandbox/node_modules/@graphql-tools/utils/index.js:960:15)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:102:15)
        at async process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:992:56)
        at async Promise.all (index 0)
        at async /sandbox/node_modules/@graphql-codegen/cli/bin.js:999:37
        at async Task.task (/sandbox/node_modules/@graphql-codegen/cli/bin.js:778:17)

  ✖ ./src/graphql/generated/graphql.tsx
    AggregateError: GraphQL Document Validation failed with 1 errors
        at new exports.AggregateError (/sandbox/node_modules/@graphql-tools/utils/index.js:898:16)
        at Object.checkValidationErrors (/sandbox/node_modules/@graphql-tools/utils/index.js:960:15)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:102:15)
        at async process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:992:56)
        at async Promise.all (index 0)
        at async /sandbox/node_modules/@graphql-codegen/cli/bin.js:999:37
        at async Task.task (/sandbox/node_modules/@graphql-codegen/cli/bin.js:778:17)
    AggregateError: GraphQL Document Validation failed with 1 errors
        at new exports.AggregateError (/sandbox/node_modules/@graphql-tools/utils/index.js:898:16)
        at Object.checkValidationErrors (/sandbox/node_modules/@graphql-tools/utils/index.js:960:15)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:102:15)
        at async process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:992:56)
        at async Promise.all (index 0)
        at async /sandbox/node_modules/@graphql-codegen/cli/bin.js:999:37
        at async Task.task (/sandbox/node_modules/@graphql-codegen/cli/bin.js:778:17)
```

**To Reproduce**
Sandbox: https://codesandbox.io/s/eager-cloud-1oz6y?file=/codegen.js
The server link is a placeholder

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}

```

2. My GraphQL operations:

```graphql
query GetUser($id: bigint!) {
  users_by_pk(id: $id) {
    updated_at
    created_a
  }
}
```

The field "

3. My `codegen.yml` config file:

```js
module.exports = {
  schema: [
    {
      "https://server.com": {
        headers: {
          "x-hasura-admin-secret": "secret"
        }
      }
    }
  ],
  documents: ["document.graphql"],
  overwrite: true,
  generates: {
    "./src/graphql/generated/graphql.tsx": {
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-react-apollo"
      ],
      config: {
        skipTypename: false,
        withHooks: true,
        withHOC: false,
        withComponent: false
      }
    },
    "./graphql.schema.json": {
      plugins: ["introspection"]
    }
  }
};

```

**Expected behavior**
I'm told that the field `created_a` doesn't exist on type User

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 14

**Comment by ngocanh1233** [comment]
I think it related to version of Graphql. I am using Graphql version "^15.0.0" and it working fine.

**Comment by n1ru4l** [comment]
This is an issue with graphql-tools/utils versions as some graphql-tools dependencies pin the exact version. I created a PR for loosening them more https://github.com/ardatan/graphql-tools/pull/3404 but it requires more internal discussion first.

For now, the best thing you can do is to use `yarn` resolutions and enforce installing `@graphql-tools/utils@^8.1.1`.

```json
{
  "resolutions": {
    "@graphql-tools/utils": "^8.1.1"
  }
}
````

https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

I have no idea about `npm` though. Sorry for the inconveniences.

**Comment by n1ru4l** [comment]
This is now fixed in the latest release 😇 Please make sure that no other dependency (besides codegen) result in installing an older graphql-tools/utils version.
