### ISSUE TITLE
Unable to create custom document loader for glob pattern source

### ISSUE THREAD

**Issue by wesselvdv** [dotansimha/graphql-code-generator#6543]
I am trying to write my own document loader to facilitate the usage of the `@export` directive from Apollo Client. I found several issues (#3939 & #2771) (even a PR #3886) that contain bits and pieces for the solution, but I figured I'd require a custom document loader because I need to filter out some variable definition requirements to prevent syntax errors. 

I am now running into the issue that the custom document loader functionality provided by GraphQL Codegen (and if I followed the code trail correctly, it's actually the custom loader functionality of `@graphql-tools/load`) is expecting a single `Source`, `string` or `GraphQLSchema` return value. This is a bit hard when I am trying to facilitate a loader for a glob pattern. This will inherently return a `Source[]` or `string[]`. 

Also, I literally tried to use the `loadDocuments` function from `@graphql-tools/load` (I noticed the arguments given to the loader are exactly the same as the ones `loadDocuments` expects.) This'll return an `Array<Source>`, and even just returning a single `Source` I keep getting the following error: 

```
    Error:
          Unable to find any GraphQL type definitions for the following pointers:

              - **/*.graphql

        at prepareResult (/workspace/node_modules/@graphql-tools/load/index.js:507:15)
        at loadTypedefs (/workspace/node_modules/@graphql-tools/load/index.js:473:12)
        at async loadDocuments (/workspace/node_modules/@graphql-codegen/cli/bin.js:540:31)
        at async /workspace/node_modules/@graphql-codegen/cli/bin.js:944:55
        at async Task.task (/workspace/node_modules/@graphql-codegen/cli/bin.js:789:17)
```

I hope I am doing it wrong, so I'd love a working example of a custom document loader for a glob pattern, but I am afraid it's not supported by `@graphql-tools/load`. If this is the case, what's the expected path to take from here?

**Comment by wesselvdv** [comment]
@dotansimha You have any pointers for me?

**Comment by dotansimha** [comment]
@wesselvdv 
I think there are 2 things here:
1 - Make the `export` directive valid - this could be done just by adding it to your schema (or, your codegen schema directly):

```
schema:
  - my-real-schema.graphql
  - "directive @export on FIELD"
```

2 - manipulate the documents (if needed), based on the usage of that directive. This could be done, as you said, with a custom operations loader.

I think there were some recent changes to the way the loader is used internally. 
@ardatan @n1ru4l can you please assist here?

**Comment by wesselvdv** [comment]
@dotansimha thanks for the reply, my issue is nr. 2 your first valid point I have already successfully done.

**Comment by ardatan** [comment]
@dotansimha It is because we no longer handle globs on `@graphql-tools/load` but inside the loaders.

**Comment by Maximaximum** [comment]
This feature would really help a lot. Currently it's a blocker for storing local app state in Apollo

**Comment by wesselvdv** [comment]
> @dotansimha It is because we no longer handle globs on `@graphql-tools/load` but inside the loaders. Not sure how to handle globs in this case 
> 
> Maybe the following code works for now at least;
> 
> ```js
> const globby = require('globby');
> module.exports = async ptr => {
>  const files = await globby(ptr);
>  return files.map(f => readFileSync(f, 'utf8'))
>  // handle files in here and return DocumetNode, GraphQLSchema or any other valid sources
> }
> ```

This exact example gives me loader errors, assuming that passing it without any adjustments should just work.

```
  Error: Failed to load custom loader: strip-apollo-export-directive
        at useCustomLoader (/workspace/node_modules/@graphql-tools/load/index.js:188:15)
        at async /workspace/node_modules/@graphql-tools/load/index.js:336:28
```

**Comment by abrenneke** [comment]
It seems to me like custom loaders just got skipped over in https://github.com/ardatan/graphql-tools/pull/3157. Would it be sufficient to just [change the lines here](https://github.com/ardatan/graphql-tools/blob/4c78b1de27f1ca5eba48e9cc24f07b19e77c63bd/packages/load/src/load-typedefs/collect-sources.ts#L106-L142) to add a check if the custom loader returned an array of sources, and if so, add all the sources to the list? Then custom loaders could function the same as the rest of the loaders (fallback loaders, if I'm reading the code correctly).

**Comment by JuroOravec** [comment]
Ran into the same issue today. 

Context:
I'm using [gridsome](https://gridsome.org/docs/querying-data/), which defined queries inside `<page-query>` and `<static-query>` custom Vue blocks.

Type safety isn't great with gridsome, so I wanted to add `graphql-codegen` to the project.

I wrote a custom loader like so

<details>
<summary>
Custom loader
</summary>

```js
const gridsomeQueryDocumentLoader = (docString, config) => {
  // Extract custom blocks
  const files = glob.sync(docString);

  const parsedGraphqlDocs = files.reduce((docsAgg, file) => {
     const fileContent = readFileSync(file, 'utf-8');
     const sfc = parseComponent(fileContent);
     const gridsomeQueryBlock = sfc.customBlocks.find(
       (block) => acceptedCustomBlockTypes.includes(block.type)
     );

     if (gridsomeQueryBlock) {
       // Parse graphql from the custom block 
       const parsedDoc = parse(gridsomeQueryBlock.content);
       docsAgg.push(parsedDoc);
     }
     return docsAgg;
   }, []);
   
   return parsedGraphqlDocs;
}

module.exports = gridsomeQueryDocumentLoader;
```
</details>

And in `codegen.yml`, I specify the target files as Vue glob

<details>
<summary>
codegen.yml
</summary>

```yml
overwrite: true
schema:
  # First run `npm run explore` to start the gridsome server
  - http://localhost:8080/___graphql
documents:
  - 'src/**/*.vue':
      loader: ./configCodegen/gridsomeQueryDocumentLoader.js
...
```
</details>

Unfortunately, this fails, because:
  1) The loader receives the glob pattern (`'src/**/*.vue'`) as input, not individual file string
  2) So I have to parse all files inside the single loader call, so I need to return an array.
  3) But as mentioned before, codegen fails when an array is returned.

**Comment by B2o5T** [comment]
Hi @JuroOravec, could you create a simple reproduction repo?

**Comment by JuroOravec** [comment]
Hi @B2o5T I'll create it this weekend

**Comment by ardatan** [comment]
Custom loaders don't support globs and I think it will never be so I'd recommend to handle it by yourself using a package like globby.

**Comment by JuroOravec** [comment]
@B2o5T This is reproduction repo https://github.com/JuroOravec/graphql-code-generator-demo-custom-loader-glob-error/tree/09797ecdd3f2ebbd16dc67947275868d9665a422. See the README for explanation and current workaround.

@ardatan I don't see why I couldn't. I'm not familiar with the internals, but since the default loader (aka no custom loader) can handle globs, the glob expansion is surely happening somewhere. And so it seems inconsistent that it's permitted for  the default loader and not for the custom ones.

**Comment by ardatan** [comment]
It is not a permission. All the loaders handle globs by themselves.

**Comment by JuroOravec** [comment]
Ok, so then how does the default loader handle it? As to me it seems there can be only two options:
  1. It is given a glob, it parses the files to graphql documents, and returns a list
  2. It is given a glob, it parses the files to graphql documents, it merges them into one, and returns that.

But based on what was said above, Option 1 is not supported, unless @abrenneke's [suggestion](https://github.com/dotansimha/graphql-code-generator/issues/6543#issuecomment-935137616) is implemented.

So is it the Option 2, that the loader merges the documents from across multiple files? Frankly, I haven't thought of it until now, but if that's a viable way to go, I'd be happy to use it in my case as well.

**Comment by JuroOravec** [comment]
Oh. My. God! Option 2 does actually work! 🎉 🎉 🎉  I wish I could've got back the time I've spent on the workaround.

**So to recap, if you're working with globs and custom loaders:**
1. Inside your loader, load the files from the glob, parse them, do your biz.
2. **IMPORTANT:** Merge them into a single document
3. Export the **single merged document**

Note: In my case, I was dealing with client-side queries, so I've joined the string definitions first with `.join('\n')`, and then `graphql.parse`'d the merged string.

@wesselvdv and @abrenneke, would this approach solve your issues too?

And @dotansimha, @ardatan, and @B2o5T, could we get this info into the docs, to help out other poor souls?

**Comment by JuroOravec** [comment]
Lastly, to give a specific example to people who might come across this thread, see the implementation of [graphql-codegen-gridsome-loader](https://github.com/JuroOravec/graphql-codegen-gridsome-loader).

**Comment by dpobel** [comment]
I'm having more or less the same problem. The loaders receives the glob pattern, so you can read the files matching it, merge their content and then parse this giant GraphQL document (like the gridsome loader, thanks @JuroOravec for the example, it helped a lot!) but then by doing that you "loose" the file structure as a result if you use near-operation-fle-preset instead of having one generated TS file per query, you end up having one big generated file which name is based on the glob pattern.

**Comment by DawidKopys** [comment]
Could we add info from @JuroOravec's comment to the documentation? For example to [the "Custom Document Loader" section](https://the-guild.dev/graphql/codegen/docs/config-reference/documents-field#custom-document-loader)?
