### ISSUE TITLE
Silent parsing error for empty query parameter

### ISSUE THREAD

**Issue by jeanlucmongrain** [dotansimha/graphql-code-generator#6749]
Suddenly, I realized that a `.graphql` file content wasn't generating at all. With no error. All other files were generated.

It's only after I turn on debug that I realized there is some syntax error:

```
[06:26:09] Load GraphQL documents [started]
GraphQLError [Object]: Syntax Error: Expected "$", found ")".
    at syntaxError (/workspace/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/workspace/node_modules/graphql/language/parser.js:1413:40)
    at Parser.parseVariable (/workspace/node_modules/graphql/language/parser.js:255:10)
    at Parser.parseVariableDefinition (/workspace/node_modules/graphql/language/parser.js:241:22)
    at Parser.optionalMany (/workspace/node_modules/graphql/language/parser.js:1503:28)
    at Parser.parseVariableDefinitions (/workspace/node_modules/graphql/language/parser.js:230:17)
    at Parser.parseOperationDefinition (/workspace/node_modules/graphql/language/parser.js:197:33)
    at Parser.parseDefinition (/workspace/node_modules/graphql/language/parser.js:137:23)
    at Parser.many (/workspace/node_modules/graphql/language/parser.js:1523:26)
    at Parser.parseDocument (/workspace/node_modules/graphql/language/parser.js:115:25) {
  locations: [ { line: 16, column: 32 } ]
}
```

Usually syntax errors cause the generator to fail... but not this one:

```graphql
query MyQuery() {
  myType {
    id
  }
}
```

My query was invalid, as nothing in `()`, I fixed my issue with:

```graphql
query MyQuery {
  myType {
    id
  }
}
```

But it show that there is an issue with generator and it silence that error

**Comment by drj17** [comment]
Just ran into a similar issue where I was missing the `$` in front of one of the args.  It seemed to just skip the file, no error or anything.

**Comment by eddeee888** [comment]
This should be fixed in the next major version because `noSilentErrors:true` is enabled by default: https://github.com/dotansimha/graphql-code-generator/pull/10496

**Comment by eddeee888** [comment]
This is fixed in this release: https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1777556900878
If the issue persists, please let me know!
