### ISSUE TITLE
typescript-urql: utils.memoize1 is not a function

### ISSUE THREAD

**Issue by ecklf** [dotansimha/graphql-code-generator#6844]
**Describe the bug**
I cannot add the latest versions to codesandbox yet, so I'll leave what I have for now.

Using the newest packages gives me the following error:

```
node_modules/@graphql-codegen/plugin-helpers/index.js:500
const getCachedDocumentNodeFromSchema = utils.memoize1(utils.getDocumentNodeFromSchema);
  
TypeError: utils.memoize1 is not a function
    at Object.<anonymous> (node_modules/@graphql-codegen/plugin-helpers/index.js:500:47)
```

**To Reproduce**
Use codegen with the packages below. Only happens on the latest packages so the schema should not matter.

**Expected behavior**
Successful build

**Environment:**

- OS: macOS 11.6 
```
"@graphql-codegen/cli": "^2.2.1",
"@graphql-codegen/typescript": "^2.2.4",
"@graphql-codegen/typescript-operations": "^2.1.8",
"@graphql-codegen/typescript-urql": "^3.2.2"
```
- NodeJS: v16.3.0

**Comment by mattleff** [comment]
I've run into this same error with the following versions and npm v6.14.13:

**Environment:**

* OS: macOS 11.5.2

```
"@graphql-codegen/add": "^3.1.0",
"@graphql-codegen/cli": "^2.2.1",
"@graphql-codegen/schema-ast": "^2.2.0",
"@graphql-codegen/typescript": "^2.2.4",
"@graphql-codegen/typescript-operations": "^2.1.8",
"@graphql-codegen/typescript-react-query": "^2.1.3",
```

* NodeJS: v14.17.0

**Comment by ecpark-danbi** [comment]
Thank you for this information!!

**Comment by capaj** [comment]
I think this should be reopened. I got this today:
```
TypeError: utils.memoize1 is not a function
    at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/plugin-helpers/index.js:502:47)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/capaj/work-repos/authier-repos/authier/node_modules/@graphql-codegen/cli/bin.js:29:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    
```
IN the file it imports `memoize1` from here:
https://github.com/ardatan/graphql-tools/blame/e7bb9810f8aa57e925ea5362e9f27b5d16d0e40f/packages/utils/src/memoize.ts#L1

this was added in version 8.4.0 I think, yet the version specified is ^8.1.1 in package.json.

Opened a PR for this here: #6957
