### ISSUE TITLE
[cli] unable to load template plugins on Windows

### ISSUE THREAD

**Issue by Diizzayy** [dotansimha/graphql-code-generator#7664]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

- [ ] 2. A failing test has been provided

- [ ] 3. A local solution has been provided

- [x] 4. A pull request is pending review

---

**Describe the bug**

the plugin loader for `@graphql-codegen/cli` fails to resolve plugins on Windows when ran programmatically.

The important part of the error output is:

> *Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs*

```sh
AggregateError: Something went wrong Unable to load template plugin matching typescript for "demo.ts"
              Unable to load template plugin matching 'typescript'.
              Reason:
                Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
```

**To Reproduce**

_Note: This issue only occurs on Windows!_

1. Create a new folder, run `npm init -y` within that folder.
2. Ensure to set `"type": "module"` in `package.json`
3. Run `npm i @graphql-codegen/cli @graphql-codegen/typescript` 
4. Within a new file `main.js`
```js
import { generate } from '@graphql-codegen/cli'

generate({
  schema: `type Query { whoAmI: String }`,
  generates: {
    ['demo.ts']: {
      plugins: ['typescript'],
    },
  },
});
```
5. Run `node main.js`

**Expected behavior**

Given the setup above, `demo.ts` should be properly generated in the root of your project.

**Environment:**

- OS: Windows 11
- `@graphql-codegen/cli`: 2.6.2
- NodeJS: v16.14.0

**Additional context**

```sh
Run node main.js
[01:25:41] Parse configuration [started]
[01:25:41] Parse configuration [completed]
[01:25:41] Generate outputs [started]
[01:25:41] Generate demo.ts [started]
[01:25:41] Load GraphQL schemas [started]
[01:25:41] Load GraphQL schemas [completed]
[01:25:41] Load GraphQL documents [started]
[01:25:41] Load GraphQL documents [completed]
[01:25:41] Generate [started]
[01:25:41] Generate [failed]
[01:25:41] → Unable to load template plugin matching typescript
[01:25:41] Generate demo.ts [failed]
[01:25:41] → Unable to load template plugin matching typescript
[01:25:41] Generate outputs [failed]
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AggregateError: Something went wrong Unable to load template plugin matching typescript for "demo.ts"
              Unable to load template plugin matching 'typescript'.
              Reason:
                Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
            
    at executeCodegen (file:///D:/a/ngl/ngl/node_modules/@graphql-codegen/cli/index.mjs:1051:2[8]
    at async generate (file:///D:/a/ngl/ngl/node_modules/@graphql-codegen/cli/index.mjs:1361:25)

Error: Unable to load template plugin matching typescript
    at getPluginByName (file:///D:/a/ngl/ngl/node_modules/@graphql-codegen/cli/index.mjs:248:23)
    at async Promise.all (index 0)
    at async file:///D:/a/ngl/ngl/node_modules/@graphql-codegen/cli/index.mjs:[9]
    at async file:///D:/a/ngl/ngl/node_modules/@graphql-codegen/cli/index.mjs:8[16]
Error: Process completed with exit code 1.
```

**Comment by Diizzayy** [comment]
@charlypoly I've realized that `@graphql-codegen/cli` fails to properly load plugin templates on windows when using ES Modules.

This chapter of the GraphQL Code Generators docs [(Using the CLI instead of core)](https://www.graphql-code-generator.com/docs/advanced/programmatic-usage#using-the-cli-instead-of-core) completely fails when ran on windows as is

```ts
import { generate } from "@graphql-codegen/cli";

generate({
    schema: "https://api.spacex.land/graphql",
    documents: "./**/*.gql",
    generates: {
      [process.cwd() + "/types.d.ts"]: {
        plugins: ["typescript"],
      },
    },
}, true);
```

When ran on windows, the code above fails, though it runs properly on all other platforms.
Ofcourse simply using `const { generate } = require("@graphql-codegen/cli");` fixes it for windows, but that isn't a suitable option

The error returned is 
```sh
AggregateError: Something went wrong Unable to load template plugin matching typescript for "C:\users\diizzayy\dev\cgen/types.ts"
              Unable to load template plugin matching 'typescript'.
              Reason:
                Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

**Comment by Diizzayy** [comment]
@dotansimha Can you provide some insight here?
