### ISSUE TITLE
anonymous queries are not supported

### ISSUE THREAD

**Issue by thunder7553** [dotansimha/graphql-code-generator#82]
Queries must be named at the moment. This will not work: 

`
{
    users {
        docReferenceId
    }
}

`error: Unable to process simple.query.graphql TypeError: Cannot read property 'value' of null
    at Object.exports.handleOperation (E:\dev\s\node_modules\graphql-code-generator\dist\operation-handler.js:18:35)
    at E:\dev\s\node_modules\graphql-code-generator\dist\codegen.js:19:56
    at Array.forEach (native)
    at Object.exports.prepareCodegen (E:\dev\s\node_modules\graphql-code-generator\dist\codegen.js:16:30)
    at Object.Transform (E:\dev\s\node_modules\graphql-code-generator\dist\transform-engine.js:26:29)
    at E:\dev\s\build\graphql.js:212:67
    at step (E:\dev\s\build\graphql.js:32:23)
    at Object.next (E:\dev\s\build\graphql.js:13:53)
    at fulfilled (E:\dev\s\build\graphql.js:4:58)`

The problem is in src/handlers/operation-handler.ts, line 27

`export const handleOperation = (schema: GraphQLSchema, definitionNode: OperationDefinitionNode, primitivesMap: any, flattenInnerTypes: boolean): CodegenDocument => {
  const name = definitionNode.name.value;
  const type = definitionNode.operation;
  const root = getRoot(schema, definitionNode);
`

There should be at least a better exception message that anonymous queries are not supported.

**Comment by dotansimha** [comment]
Fixed in `graphql-code-generator@0.5.2`! Thanks @thunder7553 !
