### ISSUE TITLE
0.4.0: Error: Unknown argument: config when following getting started instructions

### ISSUE THREAD

**Issue by jcollum-nutrien** [dotansimha/graphql-code-generator#8537]
### Describe the bug

Starting from here and following the instructions: 

https://www.the-guild.dev/graphql/codegen/docs/getting-started/installation

```
✗ yarn graphql-code-generator init


yarn run v1.22.15
warning package.json: No license field
$ /Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/.bin/graphql-code-generator init

    Welcome to GraphQL Code Generator!
    Answer few questions and we will setup everything for you.

? What type of application are you building? Backend - API or server
? Where is your schema?: (path or url) [redacted]
? Pick plugins: TypeScript (required by other typescript plugins), TypeScript Resolvers (strongly typed resolve functions)
? Where to write the output: src/generated/graphql.ts
? Do you want to generate an introspection file? Yes
? How to name the config file? codegen.ts
? What script in package.json should run the codegen? codegen
Fetching latest versions of selected plugins...

    Config file generated at codegen.ts

      $ npm install

    To install the plugins.

      $ npm run codegen

    To run GraphQL Code Generator.

✨  Done in 23.95s.

```

NOTE: strong suspicion that the downloading of the graph schema actually failed but didn't report a failure.

```


➜  gen-test git:(master) ✗ npm install
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN rm not removing /Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/.bin/semver as it wasn't installed by /Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/semver
npm WARN rm not removing /Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/.bin/mkdirp as it wasn't installed by /Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/mkdirp

> core-js@2.6.12 postinstall /Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN gen-test No description
npm WARN gen-test No repository field.
npm WARN gen-test No license field.

added 51 packages from 11 contributors, removed 49 packages, updated 468 packages and audited 519 packages in 46.403s

47 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

➜  gen-test git:(master) ✗ npm run codegen

> @ codegen /Users/justin.collum2@nutrien.com/work/tmp/gen-test
> graphql-codegen --config codegen.ts

Error: Unknown argument: config
    at Array.<anonymous> (/Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/graphql-codegen/lib/cli.js:142:31)
    at Object.self.fail (/Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/graphql-codegen/node_modules/yargs/lib/usage.js:35:17)
    at Object.self.unknownArguments (/Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/graphql-codegen/node_modules/yargs/lib/validation.js:139:13)
    at parseArgs (/Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/graphql-codegen/node_modules/yargs/yargs.js:811:32)
    at Object.get [as argv] (/Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/graphql-codegen/node_modules/yargs/yargs.js:668:16)
    at Object.<anonymous> (/Users/justin.collum2@nutrien.com/work/tmp/gen-test/node_modules/graphql-codegen/lib/cli.js:143:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ codegen: `graphql-codegen --config codegen.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ codegen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/justin.collum2@nutrien.com/.npm/_logs/2022-10-27T19_57_11_785Z-debug.log
```

### Your Example Website or App

would prefer not to, can't share company GQL endpoint

### Steps to Reproduce the Bug or Issue

1. init a new repo
1. go to https://www.the-guild.dev/graphql/codegen/docs/getting-started/installation
2. follow instructions, supply value for my company GQL endpoint
3. npm install 
4. npm run codegen

### Expected behavior

Code is generated 

### Platform

```
✗ versions
Node v14.19.2
NPM 6.14.17
Yarn 1.22.15
OS:
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83
```

package.json: 

```
{
  "devDependencies": {
    "@graphql-codegen/cli": "2.13.8",
    "@graphql-codegen/near-operation-file-preset": "2.4.3",
    "graphql-codegen": "0.4.0",
    "typescript": "4.8.4",
    "@graphql-codegen/typescript": "2.8.0",
    "@graphql-codegen/typescript-resolvers": "2.7.5",
    "@graphql-codegen/introspection": "2.2.1"
  },
  "dependencies": {
    "graphql": "16.6.0"
  },
  "scripts": {
    "codegen": "graphql-codegen --config codegen.ts"
  }
}

```

### Codegen Config File

```
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: "[redacted]",
  generates: {
    "src/generated/graphql.ts": {
      plugins: ["typescript", "typescript-resolvers"]
    },
    "./graphql.schema.json": {
      plugins: ["introspection"]
    }
  }
};

export default config;
```

**Comment by jcollum-nutrien** [comment]
This somehow just stopped happening. Wiped my node mods folder, maybe that was it?
