### ISSUE TITLE
codegen failing, without any errors

### ISSUE THREAD

**Issue by rohannair** [dotansimha/graphql-code-generator#8649]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Trying to run codegen with the following config:
```typescript
import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: 'http://localhost:8000/graphql/',
  documents: ['app/**/*.tsx'],
  generates: {
    './app/lib/graphql/_generated/': {
      preset: 'client',
      plugins: [],
    },
  },
  overwrite: true
}

export default config
```

This fails on my local server:
```bash
$ graphql-codegen
✔ Parse Configuration
❯ Generate outputs
  ❯ Generate to ./app/lib/graphql/_generated/
    ⠋ Load GraphQL schemas
    ◼ Load GraphQL documents
    ◼ Generate
@graphql-tools/load: normalizePointers [object Object]: 0.048ms
@graphql-tools/load: normalizePointers: 0.389ms
@graphql-tools/load: collectDocumentString http://localhost:8000/graphql/: 0.274ms
@graphql-tools/load: collectSources http://localhost:8000/graphql/: 0.4ms
TypeError: fetch failed
    at Object.processResponse (/Users/rohan/Work/blabla/node_modules/undici/lib/fetch/index.js:198:23)
    at /Users/rohan/Work/blabla/node_modules/undici/lib/fetch/index.js:929:38
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  message: 'fetch failed to http://localhost:8000/graphql/',
  path: undefined,
  locations: undefined,
  extensions: {
    requestBody: {
      query: 'query IntrospectionQuery {\n' +
        '  __schema {\n' +
        '    queryType {\n' +
        '      name\n' +
        '    }\n' +
        '    mutationType {\n' +
        '      name\n' +
        '    }\n' +
        '    subscriptionType {\n' +
        '      name\n' +
        '    }\n' +
        '    types {\n' +
        '      ...FullType\n' +
        '    }\n' +
        '    directives {\n' +
        '      name\n' +
        '      description\n' +
        '      locations\n' +
        '      args {\n' +
        '        ...InputValue\n' +
        '      }\n' +
        '    }\n' +
        '  }\n' +
        '}\n' +
        '\n' +
        'fragment FullType on __Type {\n' +
        '  kind\n' +
        '  name\n' +
        '  description\n' +
        '  fields(includeDeprecated: true) {\n' +
        '    name\n' +
        '    description\n' +
        '    args {\n' +
        '      ...InputValue\n' +
        '    }\n' +
        '    type {\n' +
        '      ...TypeRef\n' +
        '    }\n' +
        '    isDeprecated\n' +
        '    deprecationReason\n' +
        '  }\n' +
        '  inputFields {\n' +
        '    ...InputValue\n' +
        '  }\n' +
        '  interfaces {\n' +
        '    ...TypeRef\n' +
        '  }\n' +
        '  enumValues(includeDeprecated: true) {\n' +
        '    name\n' +
        '    description\n' +
        '    isDeprecated\n' +
        '    deprecationReason\n' +
        '  }\n' +
        '  possibleTypes {\n' +
        '    ...TypeRef\n' +
        '  }\n' +
        '}\n' +
        '\n' +
        'fragment InputValue on __InputValue {\n' +
        '  name\n' +
        '  description\n' +
        '  type {\n' +
        '    ...TypeRef\n' +
        '  }\n' +
        '  defaultValue\n' +
        '}\n' +
        '\n' +
        'fragment TypeRef on __Type {\n' +
        '  kind\n' +
        '  name\n' +
        '  ofType {\n' +
        '    kind\n' +
        '    name\n' +
        '    ofType {\n' +
        '      kind\n' +
        '      name\n' +
        '      ofType {\n' +
        '        kind\n' +
        '        name\n' +
        '        ofType {\n' +
        '          kind\n' +
        '          name\n' +
        '          ofType {\n' +
        '            kind\n' +
        '            name\n' +
        '            ofType {\n' +
        '              kind\n' +
        '              name\n' +
        '              ofType {\n' +
        '                kind\n' +
        '                name\n' +
        '              }\n' +
        '            }\n' +
        '          }\n' +
        '        }\n' +
        '      }\n' +
        '    }\n' +
        '  }\n' +
        '}',
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to ./app/lib/graphql/_generated/
    ✖
      Failed to load schema from http://localhost:8000/graphql/:
      fetch failed to http://localhost:8000/graphql/
      TypeError: fetch failed
      at Object.processResponse (/Users/rohan/Work/blabla/node_modules/undici…
      at /Users/rohan/Work/blabla/node_modules/undici/lib/fetch/index.js:929:…
      at node:internal/process/task_queues:141:7
      at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
    ◼ Load GraphQL documents
    ◼ Generate
Running lifecycle hook "afterStart" scripts...
[CLI] Loading Schemas
error Command failed with exit code 1.
```

However, if I curl the same query (assume gql.json has the same query from above, but properly formatted), it works fine:
```bash
$ curl -i -X POST http://localhost:8000/graphql/ -H "Content-Type: application/json" -d @gql.json
# returns proper response
```

The query also runs properly on GQL playground at same server:
<img width="1552" alt="Screenshot 2022-11-24 at 17 28 40" src="https://user-images.githubusercontent.com/3764902/203870374-0081aa9b-70ef-4ec7-828a-f75340fe4508.png">

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Set up codegen.ts
2. Run `yarn graphql-codegen`

### Expected behavior

Success

### Platform

- OS: macOS
- NodeJS: 17.4.0
- `graphql` version: 16.6.0
- `@graphql-codegen/cli` version(s): 2.14.0

### Codegen Config File

import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: 'http://localhost:8000/graphql/',
  documents: ['app/**/*.tsx'],
  generates: {
    './app/lib/graphql/_generated/': {
      preset: 'client',
      plugins: [],
    },
  },
  overwrite: true,
  ignoreNoDocuments: true, // for better experience with the watcher
}

export default config

**Comment by saihaj** [comment]
can you share a codesandbox or a GitHub repo so we can take a look?

**Comment by rohannair** [comment]
I got it working at 127.0.0.1. It's a work related internal service so can't publish. Will close and I'll add any other context if I come across any.
