### ISSUE TITLE
`afterAllFileWrite` hook fails on Windows when near-operation-file preset is used

### ISSUE THREAD

**Issue by jet2jet** [dotansimha/graphql-code-generator#8887]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

When using `afterAllFileWrite` hook with prettier or etc. in Windows, the invalid file path is passed to the tool and causing error.

### Your Example Website or App

https://github.com/jet2jet/graphql-code-generator-issue-hooks-failed-on-windows

### Steps to Reproduce the Bug or Issue

1. Checkout the example repository
2. Run `npm run codegen` in Windows (not in WSL)

### Expected behavior

No error has occurred (prettier success)

### Screenshots or Videos

Output is below:

```
F:\Test\gql-codegen-test\graphql-code-generator-issue-hooks-failed-on-windows>npm run codegen

> graphql-codegen-issue-template@1.0.0 codegen
> graphql-codegen --config ./codegen.ts

✔ Parse Configuration
✔ Generate outputs
Error: Command failed: prettier --write types.ts F\:/Test/gql-codegen-test/graphql-code-generator-issue-hooks-failed-on-windows/document.generated.ts
[error] No files matching the pattern were found: "F\:/Test/gql-codegen-test/graphql-code-generator-issue-hooks-failed-on-windows/document.generated.ts".

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'prettier --write types.ts F\\:/Test/gql-codegen-test/graphql-code-generator-issue-hooks-failed-on-windows/document.generated.ts'
}
```

### Platform

- OS: Windows
- NodeJS: 14.18.2
- `graphql` version: 16.2.0
- `@graphql-codegen/*` version(s): 2.13.7

### Codegen Config File

(see the repository)

### Additional context

When the file path includes spaces, the argument passed to prettier is enclosed with single quotations, which are invalid in Windows.

**Comment by Cellule** [comment]
For what it's worth, I pinpointed the problem to this line

https://github.com/dotansimha/graphql-code-generator/blob/97d734c01d88e954799c404af462de806cb9cdb6/packages/graphql-codegen-cli/src/hooks.ts#L52C3-L52C34

Where shell-quote seems to convert a path like `C:/projects/my-project/src/some-file.ts` to `C\:/projects/my-project/src/some-file.ts`
Might be related to https://github.com/ljharb/shell-quote/issues/21

All that said, I don't think it's specific to near-file-operation, the problem is that near-file-operation uses the location of the document to build an absolute path
When a generated file is a relative path, GraphQL Codegen uses the relative path as-is (except beforeOneFileWrite which uses an absolute path)
On Windows, any absolute path will fail to run in prettier (I think it's specific to prettier)

I'm honestly not 100% sure what exactly needs to be fixed, feels like a shell-quote bug more and more as I investigate

**Comment by eddeee888** [comment]
This is fixed in this release: https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1789878278469
