### ISSUE TITLE
@graphql-codegen/client-preset-swc-plugin looks for incorrect name for document types

### ISSUE THREAD

**Issue by lachieh** [dotansimha/graphql-code-generator#9138]
### Which packages are impacted by your issue?

@graphql-codegen/client-preset-swc-plugin

### Describe the bug

Looks like the `@graphql-codegen/client-preset-swc-plugin` isn't looking for the correct type name when it the query/mutation name starts with a lowercase.

In the example, the generated document variable is capitalized as `GetUserDocument`, whereas the swc plugin is looking for the original name. Changing the query to a capital works fine.

```
"getUserDocument" is not exported by "graphql/graphql.ts", imported by "src/App.tsx".
file: /project/sandbox/src/App.tsx:2:9
1: import { jsx as _jsx } from "react/jsx-runtime";
2: import { getUserDocument } from "../graphql/graphql";
            ^
3: const EXAMPLE_QUERY = getUserDocument;
4: function test(doc) {
error during build:
RollupError: "getUserDocument" is not exported by "graphql/graphql.ts", imported by "src/App.tsx".
    at error (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:2105:30)
    at Module.error (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:13174:16)
    at Module.traceVariable (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:13559:29)
    at ModuleScope.findVariable (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:12061:39)
    at Identifier.bind (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:7933:40)
    at VariableDeclarator.bind (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:5726:23)
    at VariableDeclaration.bind (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:5722:28)
    at Program.bind (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:5722:28)
    at Module.bindReferences (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:13170:18)
    at Graph.sortModules (file:///project/sandbox/node_modules/rollup/dist/es/shared/node-entry.js:24505:20)
```

### Your Example Website or App

https://codesandbox.io/p/sandbox/nervous-jepsen-mw8exq

### Steps to Reproduce the Bug or Issue

In the example, run the `npm run start` command

Error:
```graphql
query getUser {
  user(id: 1) {
    id
  }
}
```

Works:
```diff
- query getUser {
+ query GetUser {
    user(id: 1) {
      id
    }
  }
```

### Expected behavior

I would expect that I can use a query starting with a lowercase letter.

**Comment by lachieh** [comment]
Looks like this was resolved in #9060

**Comment by lachieh** [comment]
Tagging @JesseVelden, sorry if you get multiple notifications

**Comment by saihaj** [comment]
I just released [`@graphql-codegen/client-preset-swc-plugin@0.1.2`](https://www.npmjs.com/package/@graphql-codegen/client-preset-swc-plugin/v/0.1.2) let me know if that fixes this issue

**Comment by lachieh** [comment]
@saihaj that has done it! And thanks @JesseVelden for your work. Much appreciated!
